import fs from 'node:fs';
import path from 'node:path';
import type { ScenarioEvent } from '../../types/scenario';

export interface ExportResult {
  success: boolean;
  filePath: string;
  markdownContent: string;
  error?: string;
}

export function convertEventsToMarkdown(events: ScenarioEvent[], prompt: string): string {
  const lines: string[] = [];

  lines.push(`# Implementation Plan: ${prompt}`);
  lines.push('');
  lines.push(`> Generated by Zenith AI Planner on ${new Date().toISOString().split('T')[0]}`);
  lines.push('');

  events.forEach((event) => {
    switch (event.kind) {
      case 'analysis':
        lines.push(`## ${event.title}`);
        lines.push('');
        event.sections.forEach((section) => {
          lines.push(`### ${section.title}`);
          section.items.forEach((item) => {
            lines.push(`- ${item}`);
          });
          lines.push('');
        });
        break;

      case 'summary':
        lines.push(`## Executive Summary`);
        lines.push('');
        lines.push(`**${event.title}**`);
        if (event.description) {
          lines.push('');
          lines.push(event.description);
        }
        lines.push('');
        if (event.verified && event.verified.length > 0) {
          lines.push('### Verification Items');
          for (const v of event.verified) {
            lines.push(`- ✔ ${v}`);
          }
          lines.push('');
        }
        break;

      case 'terminal':
        lines.push('```bash');
        lines.push(`# ${event.command}`);
        if (event.output && event.output.length > 0) {
          for (const out of event.output) {
            lines.push(out);
          }
        }
        lines.push('```');
        lines.push('');
        break;

      default:
        break;
    }
  });

  lines.push('---');
  lines.push('*End of implementation plan.*');

  return lines.join('\n');
}

export function savePlanToFile(
  events: ScenarioEvent[],
  prompt: string,
  targetDirectory: string = process.cwd(),
  filename: string = 'implementation-plan.md',
): ExportResult {
  try {
    const plansDir = path.join(targetDirectory, 'zenith_plans');

    if (!fs.existsSync(plansDir)) {
      fs.mkdirSync(plansDir, { recursive: true });
    }

    const markdownContent = convertEventsToMarkdown(events, prompt);
    const fullFilePath = path.join(plansDir, filename);
    const relativeDisplayPath = path.join('zenith_plans', filename);

    fs.writeFileSync(fullFilePath, markdownContent, 'utf-8');

    return {
      success: true,
      filePath: relativeDisplayPath,
      markdownContent,
    };
  } catch (err: unknown) {
    const errorMessage = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      filePath: path.join('zenith_plans', filename),
      markdownContent: '',
      error: errorMessage,
    };
  }
}
