import fs from 'node:fs';
import path from 'node:path';
import type { ScenarioEvent } from '../../types/scenario';

export interface ExportResult {
  success: boolean;
  filePath: string;
  markdownContent: string;
  error?: string;
}

export function convertEventsToMarkdown(events: ScenarioEvent[], prompt: string): string {
  const lines: string[] = [];

  lines.push(`# Implementation Plan: ${prompt}`);
  lines.push('');
  lines.push(`> Generated by Zenith AI Planner on ${new Date().toISOString().split('T')[0]}`);
  lines.push('');

  for (const event of events) {
    switch (event.kind) {
      case 'analysis':
        lines.push(`## ${event.title}`);
        lines.push('');
        for (const section of event.sections) {
          lines.push(`### ${section.title}`);
          for (const item of section.items) {
            lines.push(`- ${item}`);
          }
          lines.push('');
        }
        break;

      case 'summary':
        lines.push('## Executive Summary');
        lines.push('');
        lines.push(`**${event.title}**`);
        if (event.description) {
          lines.push('');
          lines.push(event.description);
        }
        lines.push('');
        if (event.filesCreated.length > 0) {
          lines.push('### Files Created');
          for (const f of event.filesCreated) {
            lines.push(`- \`${f}\``);
          }
          lines.push('');
        }
        if (event.commandsExecuted.length > 0) {
          lines.push('### Commands Executed');
          for (const c of event.commandsExecuted) {
            lines.push(`- \`${c}\``);
          }
          lines.push('');
        }
        if (event.verified && event.verified.length > 0) {
          lines.push('### Verification Items');
          for (const v of event.verified) {
            lines.push(`- ✔ ${v}`);
          }
          lines.push('');
        }
        break;

      case 'terminal':
        lines.push('```bash');
        lines.push(`# ${event.command}`);
        if (event.output && event.output.length > 0) {
          for (const out of event.output) {
            lines.push(out);
          }
        }
        lines.push('```');
        lines.push('');
        break;

      case 'thinking':
        lines.push('## Chain of Thought');
        lines.push('');
        for (const thought of event.thoughts) {
          const text = typeof thought === 'string' ? thought : thought.text;
          lines.push(`> ${text}`);
          lines.push('');
        }
        break;

      case 'file_create':
        lines.push(`### File Created: \`${event.filePath}\``);
        lines.push('');
        if (event.lines.length > 0) {
          lines.push(`\`\`\`${event.language}`);
          for (const line of event.lines) {
            lines.push(line.text);
          }
          lines.push('```');
          lines.push('');
        }
        break;

      case 'file_edit':
        lines.push(`### File Edited: \`${event.filePath}\``);
        lines.push('');
        if (event.removedLines.length > 0) {
          lines.push('**Removed:**');
          lines.push('```diff');
          for (const line of event.removedLines) {
            lines.push(`- ${line.text}`);
          }
          for (const line of event.addedLines) {
            lines.push(`+ ${line.text}`);
          }
          lines.push('```');
          lines.push('');
        }
        break;

      case 'file_delete':
        lines.push(`### File Deleted: \`${event.filePath}\``);
        lines.push('');
        break;

      case 'error':
        lines.push(`### Error: ${event.message}`);
        lines.push('');
        if (event.command) {
          lines.push(`Command: \`${event.command}\``);
          lines.push('');
        }
        if (event.stack) {
          lines.push('<details>');
          lines.push('<summary>Stack Trace</summary>');
          lines.push('');
          lines.push('```');
          lines.push(event.stack);
          lines.push('```');
          lines.push('</details>');
          lines.push('');
        }
        break;

      case 'warning':
        lines.push(`> ⚠️ **Warning:** ${event.message}`);
        if (event.details) {
          lines.push(`> ${event.details}`);
        }
        lines.push('');
        break;

      case 'retry':
        lines.push(`> 🔄 Retry attempt #${event.attempt}: ${event.message}`);
        lines.push('');
        break;

      case 'success':
        lines.push(`### ✅ ${event.message}`);
        lines.push('');
        if (event.filesCreated.length > 0) {
          lines.push('**Files Created:**');
          for (const f of event.filesCreated) {
            lines.push(`- \`${f}\``);
          }
          lines.push('');
        }
        if (event.commandsExecuted.length > 0) {
          lines.push('**Commands:**');
          for (const c of event.commandsExecuted) {
            lines.push(`- \`${c}\``);
          }
          lines.push('');
        }
        break;

      case 'message':
        lines.push(event.text);
        lines.push('');
        break;

      case 'progress':
        lines.push(`### ${event.label}`);
        lines.push('');
        for (const step of event.steps) {
          const icon =
            step.status === 'done' ? '✔' : step.status === 'error' ? '✖' : step.status === 'active' ? '▸' : '○';
          lines.push(`- ${icon} ${step.label}`);
        }
        lines.push('');
        break;

      case 'test_execution':
        lines.push(`### Test Results: \`${event.command}\``);
        lines.push('');
        lines.push(`Framework: ${event.framework}`);
        lines.push('');
        lines.push(
          `**${event.summary.passed}** passed, **${event.summary.failed}** failed, **${event.summary.skipped}** skipped (${event.summary.total} total)`,
        );
        lines.push('');
        if (event.results.length > 0) {
          lines.push('| Test | Status | Duration |');
          lines.push('|------|--------|----------|');
          for (const r of event.results) {
            const status = r.status === 'pass' ? '✔ pass' : r.status === 'fail' ? '✖ fail' : '○ skip';
            const duration = r.duration ? `${r.duration}ms` : '-';
            lines.push(`| ${r.name} | ${status} | ${duration} |`);
          }
          lines.push('');
        }
        break;

      case 'build_step':
        lines.push(`### Build Step: ${event.step} [${event.status}]`);
        lines.push('');
        if (event.output && event.output.length > 0) {
          lines.push('```');
          for (const out of event.output) {
            lines.push(out);
          }
          lines.push('```');
          lines.push('');
        }
        break;

      case 'deployment':
        lines.push(`### Deployment: ${event.target} [${event.status}]`);
        lines.push('');
        if (event.url) {
          lines.push(`URL: ${event.url}`);
          lines.push('');
        }
        if (event.output && event.output.length > 0) {
          lines.push('```');
          for (const out of event.output) {
            lines.push(out);
          }
          lines.push('```');
          lines.push('');
        }
        break;

      case 'planner_action_panel':
        lines.push(`### Plan Export: \`${event.defaultFilename}\``);
        lines.push('');
        if (event.saved) {
          lines.push('*Plan saved successfully.*');
          lines.push('');
        }
        break;

      case 'mode_mismatch':
        lines.push(
          `> ⚠️ Mode mismatch: Current mode is **${event.currentMode}**, but **${event.suggestedMode}** is recommended.`,
        );
        lines.push(`> ${event.reason}`);
        lines.push('');
        break;

      case 'waiting':
        break;
    }
  }

  lines.push('---');
  lines.push('*End of implementation plan.*');

  return lines.join('\n');
}

export function savePlanToFile(
  events: ScenarioEvent[],
  prompt: string,
  targetDirectory: string = process.cwd(),
  filename: string = 'implementation-plan.md',
): ExportResult {
  try {
    const plansDir = path.join(targetDirectory, 'zenith_plans');

    if (!fs.existsSync(plansDir)) {
      fs.mkdirSync(plansDir, { recursive: true });
    }

    const markdownContent = convertEventsToMarkdown(events, prompt);
    const fullFilePath = path.join(plansDir, filename);
    const relativeDisplayPath = path.join('zenith_plans', filename);

    fs.writeFileSync(fullFilePath, markdownContent, 'utf-8');

    return {
      success: true,
      filePath: relativeDisplayPath,
      markdownContent,
    };
  } catch (err: unknown) {
    const errorMessage = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      filePath: path.join('zenith_plans', filename),
      markdownContent: '',
      error: errorMessage,
    };
  }
}
