import fs from 'node:fs';
import path from 'node:path';
import type { ScenarioEvent } from '../../types/scenario';

interface ExportResult {
  success: boolean;
  filePath: string;
  markdownContent: string;
  error?: string;
}

function convertEventsToMarkdown(events: ScenarioEvent[], prompt: string): string {
  const lines: string[] = [];

  lines.push(`# Implementation Plan: ${prompt}`);
  lines.push('');
  lines.push(`> Generated by Zenith AI Planner on ${new Date().toISOString().split('T')[0]}`);
  lines.push('');

  for (const event of events) {
    switch (event.kind) {
      case 'thinking':
        lines.push('## Chain of Thought');
        lines.push('');
        for (const thought of event.thoughts) {
          const text = typeof thought === 'string' ? thought : thought.text;
          lines.push(`> ${text}`);
          lines.push('');
        }
        break;

      case 'message':
        lines.push(event.text);
        lines.push('');
        break;

      case 'tool_call':
        lines.push(`### Tool Call: \`${event.tool}\``);
        lines.push('');
        if (Object.keys(event.params).length > 0) {
          lines.push('```json');
          lines.push(JSON.stringify(event.params, null, 2));
          lines.push('```');
          lines.push('');
        }
        break;

      case 'tool_result':
        lines.push(`### Tool Result: \`${event.tool}\` ${event.success ? '(success)' : '(failed)'}`);
        lines.push('');
        if (event.output) {
          lines.push('```');
          lines.push(event.output);
          lines.push('```');
          lines.push('');
        }
        if (event.error) {
          lines.push(`Error: ${event.error}`);
          lines.push('');
        }
        break;

      case 'error':
        lines.push(`### Error: ${event.message}`);
        lines.push('');
        if (event.code) {
          lines.push(`Code: \`${event.code}\``);
          lines.push('');
        }
        if (event.provider) {
          lines.push(`Provider: \`${event.provider}\``);
          lines.push('');
        }
        if (event.recoverable) {
          lines.push('> This error may be recoverable. You can retry or switch providers.');
          lines.push('');
        }
        break;

      case 'warning':
        lines.push(`> **Warning:** ${event.message}`);
        if (event.code) {
          lines.push(`> Code: ${event.code}`);
        }
        lines.push('');
        break;

      case 'success':
        lines.push(`### ${event.message}`);
        lines.push('');
        if (event.iterations !== undefined) {
          lines.push(`Iterations: ${event.iterations}`);
          lines.push('');
        }
        if (event.tokenInfo) {
          lines.push(`Tokens used: ${event.tokenInfo.used}`);
          lines.push('');
        }
        break;

      case 'progress':
        lines.push(`### ${event.label}`);
        lines.push('');
        for (const step of event.steps) {
          const icon =
            step.status === 'done' ? '✔' : step.status === 'error' ? '✖' : step.status === 'active' ? '▸' : '○';
          lines.push(`- ${icon} ${step.label}`);
        }
        lines.push('');
        break;

      case 'confirmation_request':
        lines.push(`### Confirmation Required: \`${event.tool}\``);
        lines.push('');
        lines.push(`${event.message}`);
        lines.push('');
        break;
    }
  }

  lines.push('---');
  lines.push('*End of implementation plan.*');

  return lines.join('\n');
}

export function savePlanToFile(
  events: ScenarioEvent[],
  prompt: string,
  targetDirectory: string = process.cwd(),
  filename: string = 'implementation-plan.md',
): ExportResult {
  try {
    const plansDir = path.join(targetDirectory, 'zenith_plans');

    if (!fs.existsSync(plansDir)) {
      fs.mkdirSync(plansDir, { recursive: true });
    }

    const markdownContent = convertEventsToMarkdown(events, prompt);
    const fullFilePath = path.join(plansDir, filename);
    const relativeDisplayPath = path.join('zenith_plans', filename);

    fs.writeFileSync(fullFilePath, markdownContent, 'utf-8');

    return {
      success: true,
      filePath: relativeDisplayPath,
      markdownContent,
    };
  } catch (err: unknown) {
    const errorMessage = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      filePath: path.join('zenith_plans', filename),
      markdownContent: '',
      error: errorMessage,
    };
  }
}
