DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8765
HOST_ENV_VAR = "ZENITH_HOST"
PORT_ENV_VAR = "ZENITH_PORT"

WS_PATH = "/ws"
HEALTH_PATH = "/health"
METRICS_PATH = "/metrics"

API_PREFIX = "/api"
CONFIG_PATH = "/api/config"
SESSIONS_PATH = "/api/sessions"

DEFAULT_BASH_TIMEOUT = 120
DEFAULT_MAX_ITERATIONS = 100
CONTEXT_SUMMARY_THRESHOLD = 0.85

DEFAULT_PROVIDER = "openrouter"
DEFAULT_MODE = "build"
PLAN_MODE = "plan"
BUILD_MODE = "build"
