DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8765
HOST_ENV_VAR = "ZENITH_HOST"
PORT_ENV_VAR = "ZENITH_PORT"
WS_PATH = "/ws"
HEALTH_PATH = "/health"
DEFAULT_BASH_TIMEOUT = 120
CONTEXT_SUMMARY_THRESHOLD = 0.85
