-- 004: catalog seed data + behavior columns
--
-- The curated provider/model catalog is SQL-only (no provider/model names live
-- in Python). This file both creates the behavior columns used by the runtime
-- (env keys, base_url style, popularity, prompt caching, thinking headers,
-- tokenizer, prompt tier) and upserts the seed rows.
--
-- Idempotent: this file is tracked in schema_migrations and applied once per
-- database; the ALTERs follow the same plain-ADD-COLUMN convention as 002.
-- The seed rows use INSERT ... ON CONFLICT DO UPDATE so existing DBs seeded by
-- the old Python path get refreshed with the new metadata on upgrade.

-- Behavior columns on catalog_providers
ALTER TABLE catalog_providers ADD COLUMN env_keys_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE catalog_providers ADD COLUMN is_popular INTEGER NOT NULL DEFAULT 0;
ALTER TABLE catalog_providers ADD COLUMN base_url_style TEXT NOT NULL DEFAULT '';
ALTER TABLE catalog_providers ADD COLUMN supports_prompt_caching INTEGER NOT NULL DEFAULT 0;
ALTER TABLE catalog_providers ADD COLUMN supports_thinking_headers INTEGER NOT NULL DEFAULT 0;
ALTER TABLE catalog_providers ADD COLUMN custom_flow INTEGER NOT NULL DEFAULT 0;

-- Behavior columns on catalog_models
ALTER TABLE catalog_models ADD COLUMN tokenizer TEXT NOT NULL DEFAULT '';
ALTER TABLE catalog_models ADD COLUMN prompt_tier TEXT NOT NULL DEFAULT '';

-- ─────────────────────────────────────────────────────────────
-- Providers
-- ─────────────────────────────────────────────────────────────
INSERT INTO catalog_providers (id, name, description, adapter, litellm_prefix, default_model, base_url, api_key_prefix, requires_api_key, swatch_json, capabilities_json, config_fields_json, options_json, env_keys_json, is_popular, base_url_style, supports_prompt_caching, supports_thinking_headers, custom_flow, sort_order) VALUES
    ('openrouter', 'OpenRouter', 'Free tier inference via OpenRouter. OpenAI-compatible API with native function calling. All models use the :free suffix.', 'openrouter', 'openai/', 'openrouter/free', 'https://openrouter.ai/api/v1', 'sk-or-v1-', 1, '["#7000FF", "#A033FF", "#6000DF"]', '{"streaming": true, "thinking": true, "function_calling": true}', '[{"key": "apiKey", "label": "API Key", "type": "password", "required": true, "placeholder": "sk-or-v1-..."}, {"key": "baseUrl", "label": "Base URL", "type": "text", "defaultValue": "https://openrouter.ai/api/v1"}, {"key": "timeout", "label": "Timeout (ms)", "type": "number", "defaultValue": 30000}]', '{}', '["OPENROUTER_API", "openrouter_api", "OPENROUTER_API_KEY"]', 1, '', 0, 0, 0, 0),
    ('tokenrouter', 'TokenRouter', 'TokenRouter unified OpenAI-compatible LLM gateway with Moonshot AI Kimi K3 and other models', 'openai_compatible', 'openai/', 'moonshotai/kimi-k3-free', 'https://api.tokenrouter.com/v1', 'sk-', 1, '["#00A67E", "#008C6A", "#00664D"]', '{"streaming": true, "thinking": true, "function_calling": true}', '[{"key": "baseUrl", "label": "Base URL", "type": "text", "required": true, "defaultValue": "https://api.tokenrouter.com/v1", "placeholder": "https://api.tokenrouter.com/v1"}, {"key": "apiKey", "label": "TokenRouter API Key", "type": "password", "required": true, "placeholder": "sk-..."}, {"key": "model", "label": "Model ID", "type": "text", "required": true, "defaultValue": "moonshotai/kimi-k3-free", "placeholder": "moonshotai/kimi-k3-free"}]', '{}', '["TOKENROUTER_API_KEY", "tokenrouter_api_key"]', 0, 'tokenrouter', 0, 0, 0, 1),
    ('openai_compatible', 'OpenAI Compatible', 'Custom OpenAI-compatible API endpoint (TokenRouter, vLLM, Ollama, LM Studio, etc.)', 'openai_compatible', 'openai/', 'moonshotai/kimi-k3-free', 'https://api.tokenrouter.com/v1', 'sk-', 1, '["#00A67E", "#008C6A", "#00664D"]', '{"streaming": true, "thinking": true, "function_calling": true}', '[{"key": "baseUrl", "label": "Base URL", "type": "text", "required": true, "defaultValue": "https://api.tokenrouter.com/v1", "placeholder": "https://api.tokenrouter.com/v1"}, {"key": "apiKey", "label": "OpenAI Compatible API Key", "type": "password", "required": true, "placeholder": "sk-..."}, {"key": "model", "label": "Model ID", "type": "text", "required": true, "defaultValue": "moonshotai/kimi-k3-free", "placeholder": "moonshotai/kimi-k3-free"}]', '{}', '["OPENAI_API_KEY", "openai_api_key"]', 0, 'user', 0, 0, 1, 2),
    ('openai', 'OpenAI', 'Official OpenAI GPT series models', 'openai_compat', 'openai/', 'gpt-4o-mini', 'https://api.openai.com/v1', 'sk-', 1, '["#10A37F", "#1A7F64", "#0D8C6D"]', '{"streaming": true, "thinking": true, "function_calling": true}', '[{"key": "apiKey", "label": "API Key", "type": "password", "required": true, "placeholder": "sk-..."}, {"key": "baseUrl", "label": "Base URL", "type": "text", "defaultValue": "https://api.openai.com/v1"}, {"key": "timeout", "label": "Timeout (ms)", "type": "number", "defaultValue": 30000}]', '{}', '["OPENAI_API_KEY", "openai_api_key"]', 1, '', 0, 0, 0, 3),
    ('nvidia', 'NVIDIA AI', 'NVIDIA NIM microservices & high-performance LLM catalog', 'nvidia', 'nvidia_nim/', 'nvidia/nemotron-3-ultra-550b-a55b', 'https://integrate.api.nvidia.com/v1', 'nvapi-', 1, '["#76B900", "#5C9900", "#447700"]', '{"streaming": true, "thinking": true, "function_calling": true}', '[{"key": "apiKey", "label": "API Key", "type": "password", "required": true, "placeholder": "nvapi-..."}, {"key": "baseUrl", "label": "Base URL", "type": "text", "defaultValue": "https://integrate.api.nvidia.com/v1"}, {"key": "timeout", "label": "Timeout (ms)", "type": "number", "defaultValue": 30000}]', '{}', '["NVIDIA_AI_API_KEY", "nvidia_ai_api_key", "NVIDIA_API_KEY"]', 1, '', 0, 0, 0, 4),
    ('groq', 'Groq', 'Ultra-fast inference on Groq LPU. OpenAI-compatible API with function calling support. Free tier: 30 RPM, 1K RPD on most models.', 'groq', 'groq/', 'llama-3.3-70b-versatile', 'https://api.groq.com/openai/v1', 'gsk_', 1, '["#F55036", "#FF6B52", "#E03A24"]', '{"streaming": true, "thinking": false, "function_calling": true}', '[{"key": "apiKey", "label": "API Key", "type": "password", "required": true, "placeholder": "gsk_..."}, {"key": "baseUrl", "label": "Base URL", "type": "text", "defaultValue": "https://api.groq.com/openai/v1"}, {"key": "timeout", "label": "Timeout (ms)", "type": "number", "defaultValue": 30000}]', '{}', '["GROQ_API_KEY", "groq_api_key"]', 1, '', 0, 0, 0, 5),
    ('anthropic', 'Anthropic', 'Official Anthropic Claude family models', 'openai_compat', 'anthropic/', 'claude-sonnet-4-20250514', 'https://api.anthropic.com', 'sk-ant-', 1, '["#D97706", "#B45309", "#92400E"]', '{"streaming": true, "thinking": true, "function_calling": true}', '[{"key": "apiKey", "label": "API Key", "type": "password", "required": true, "placeholder": "sk-ant-..."}, {"key": "baseUrl", "label": "Base URL", "type": "text", "defaultValue": "https://api.anthropic.com"}, {"key": "timeout", "label": "Timeout (ms)", "type": "number", "defaultValue": 30000}]', '{}', '["ANTHROPIC_API_KEY", "anthropic_api_key"]', 1, '', 1, 1, 0, 6),
    ('google', 'Google AI Studio', 'Google Gemini AI models via AI Studio. Free tier with generous quotas. Supports thinking, function calling, multimodal.', 'gemini', 'gemini/', 'gemini-3.5-flash-lite', 'https://generativelanguage.googleapis.com', 'AQ.', 1, '["#4285F4", "#34A853", "#FBBC05"]', '{"streaming": true, "thinking": true, "function_calling": true}', '[{"key": "apiKey", "label": "API Key", "type": "password", "required": true, "placeholder": "AIzaSy..."}, {"key": "baseUrl", "label": "Base URL", "type": "text", "defaultValue": "https://generativelanguage.googleapis.com"}, {"key": "timeout", "label": "Timeout (ms)", "type": "number", "defaultValue": 60000}]', '{}', '["GOOGLE_AI_STUDIO", "google_ai_studio", "GOOGLE_API_KEY", "GEMINI_API_KEY"]', 1, 'gemini', 0, 0, 0, 7),
    ('custom', 'Custom OpenAI-Compatible', 'Self-hosted Ollama, vLLM, or custom server', 'openai_compat', '', 'llama3', 'http://localhost:11434/v1', NULL, 0, '["#6B7280", "#4B5563", "#374151"]', '{"streaming": true, "thinking": true, "function_calling": true}', '[{"key": "baseUrl", "label": "Base URL", "type": "text", "required": true, "placeholder": "http://localhost:11434/v1"}, {"key": "apiKey", "label": "API Key", "type": "password", "placeholder": "Optional"}, {"key": "model", "label": "Model Name", "type": "text", "required": true, "placeholder": "e.g. llama3"}, {"key": "timeout", "label": "Timeout (ms)", "type": "number", "defaultValue": 30000}]', '{}', '["OPENAI_API_KEY", "openai_api_key"]', 0, 'user', 0, 0, 1, 8)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    description = excluded.description,
    adapter = excluded.adapter,
    litellm_prefix = excluded.litellm_prefix,
    default_model = excluded.default_model,
    base_url = excluded.base_url,
    api_key_prefix = excluded.api_key_prefix,
    requires_api_key = excluded.requires_api_key,
    swatch_json = excluded.swatch_json,
    capabilities_json = excluded.capabilities_json,
    config_fields_json = excluded.config_fields_json,
    options_json = excluded.options_json,
    env_keys_json = excluded.env_keys_json,
    is_popular = excluded.is_popular,
    base_url_style = excluded.base_url_style,
    supports_prompt_caching = excluded.supports_prompt_caching,
    supports_thinking_headers = excluded.supports_thinking_headers,
    custom_flow = excluded.custom_flow,
    sort_order = excluded.sort_order
;

-- ─────────────────────────────────────────────────────────────
-- Models
-- ─────────────────────────────────────────────────────────────
INSERT INTO catalog_models (provider_id, id, name, description, context_window, parameters, architecture, input_modalities, output_modalities, tags, model_capabilities_json, speed_tier, best_for, pricing_json, is_default, tokenizer, prompt_tier) VALUES
    ('openrouter', 'openrouter/free', 'Free Models Router', 'Meta router that randomly selects from available free models. Supports tool calling, structured output, and reasoning. Model varies per request.', 131072, 'varies', 'Router (meta)', '["text"]', '["text"]', '["router", "free", "meta", "default"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": false}', 'fast', '["free tier", "exploration", "general purpose"]', '{"input": 0.0, "output": 0.0}', 1, '', 'flagship'),
    ('openrouter', 'poolside/laguna-xs-2.1:free', 'Poolside Laguna XS 2.1', 'Poolside 33B MoE. Free on OpenRouter. Good code quality. May be slow. Verified: connects, FC works.', 262144, '33B (MoE)', 'Mixture of Experts', '["text"]', '["text"]', '["free", "coding", "agentic"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": false}', 'moderate', '["agentic coding", "tool-heavy workflows", "free tier"]', '{"input": 0.0, "output": 0.0}', 0, '', 'flagship'),
    ('openrouter', 'poolside/laguna-s-2.1:free', 'Poolside Laguna S 2.1', 'Poolside larger S variant. Free on OpenRouter. Stronger reasoning than XS. Verified: connects, FC works.', 262144, 'unknown', 'Mixture of Experts', '["text"]', '["text"]', '["free", "coding", "reasoning"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": false}', 'moderate', '["complex coding", "reasoning tasks", "free tier"]', '{"input": 0.0, "output": 0.0}', 0, '', 'flagship'),
    ('openrouter', 'cohere/north-mini-code:free', 'Cohere North Mini Code', 'Cohere code-focused mini model. Free on OpenRouter. Supports tools and reasoning. Verified: connects, FC works.', 131072, 'unknown', 'Dense Transformer', '["text"]', '["text"]', '["free", "code", "coding"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": false}', 'fast', '["code generation", "code explanation", "free tier"]', '{"input": 0.0, "output": 0.0}', 0, '', 'compact'),
    ('tokenrouter', 'moonshotai/kimi-k3-free', 'Kimi K3 Free (Moonshot)', 'Free compute capacity is limited. Service stability and concurrency are not guaranteed.', 128000, NULL, NULL, '["text"]', '["text"]', '[]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": true}', 'fast', '["reasoning", "coding", "general"]', '{"input": 0.0, "output": 0.0}', 1, '', 'flagship'),
    ('openai_compatible', 'moonshotai/kimi-k3-free', 'Kimi K3 Free (Moonshot)', 'Free compute capacity is limited. Service stability and concurrency are not guaranteed.', 128000, NULL, NULL, '["text"]', '["text"]', '[]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": true}', 'fast', '["reasoning", "coding", "general"]', '{"input": 0.0, "output": 0.0}', 1, '', 'flagship'),
    ('openai', 'gpt-4o-mini', 'GPT-4o Mini', 'Fast, affordable flagship small model. Default choice for everyday work.', 128000, 'unknown', 'Dense Transformer', '["text", "image"]', '["text"]', '["fast", "default", "production"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": false}', 'fast', '["general purpose", "coding", "quick responses"]', '{"input": 0.15, "output": 0.6, "cache_read": 0.075}', 1, 'o200k_base', 'compact'),
    ('openai', 'gpt-4o', 'GPT-4o', 'High-quality multimodal flagship model.', 128000, 'unknown', 'Dense Transformer', '["text", "image", "audio"]', '["text"]', '["multimodal", "production", "high-quality"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": false}', 'moderate', '["complex tasks", "multimodal analysis", "production code"]', '{"input": 2.5, "output": 10.0, "cache_read": 1.25}', 0, 'o200k_base', 'flagship'),
    ('openai', 'o3-mini', 'o3-mini', 'Compact reasoning model. Strong at STEM and coding with reasoning effort control.', 200000, 'unknown', 'Reasoning Transformer', '["text"]', '["text"]', '["reasoning", "coding"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": true}', 'moderate', '["reasoning", "STEM", "complex coding"]', '{"input": 1.1, "output": 4.4, "cache_read": 0.55}', 0, 'o200k_base', 'reasoning'),
    ('openai', 'o4-mini', 'o4-mini', 'Latest compact reasoning model with tool calling support.', 200000, 'unknown', 'Reasoning Transformer', '["text", "image"]', '["text"]', '["reasoning", "coding"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": true}', 'moderate', '["reasoning", "agentic coding", "tool use"]', '{"input": 1.1, "output": 4.4, "cache_read": 0.55}', 0, 'o200k_base', 'compact'),
    ('nvidia', 'nvidia/nemotron-3-ultra-550b-a55b', 'Nemotron-3 Ultra 550B', 'NVIDIA''s flagship 550B MoE model. Best quality across all benchmarks. Creates complete test suites, docstrings, type hints, error handling. Self-recovers from errors.', 131072, '550B (A55B active)', 'Mixture of Experts', '["text"]', '["text"]', '["frontier", "coding", "reasoning", "agent", "best-quality"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": true}', 'moderate', '["complex coding", "multi-step agentic tasks", "production code", "test generation"]', '{"input": 0.0, "output": 0.0}', 1, '', 'reasoning'),
    ('nvidia', 'nvidia/nemotron-3-super-120b-a12b', 'Nemotron-3 Super 120B', 'Fast 120B MoE model with solid coding ability. Good at creating files with docstrings and type hints.', 131072, '120B (A12B active)', 'Mixture of Experts', '["text"]', '["text"]', '["fast", "coding", "reasoning", "agent"]', '{"function_calling": true, "structured_output": false, "reasoning": true, "thinking": true}', 'fast', '["quick coding tasks", "file generation", "simple agentic workflows"]', '{"input": 0.0, "output": 0.0}', 0, '', 'reasoning'),
    ('nvidia', 'nvidia/nemotron-3-nano-30b-a3b', 'Nemotron-3 Nano 30B', 'Ultra-lightweight 30B MoE. Very fast (2-20s). Excellent code quality when using tools.', 131072, '30B (A3B active)', 'Mixture of Experts', '["text"]', '["text"]', '["ultra-fast", "lightweight", "agent", "native-function-calling"]', '{"function_calling": true, "structured_output": false, "reasoning": true, "thinking": true}', 'fast', '["quick responses", "simple tasks", "batch processing"]', '{"input": 0.0, "output": 0.0}', 0, '', 'reasoning'),
    ('nvidia', 'nvidia/llama-3.3-nemotron-super-49b-v1', 'Nemotron Super 49B', 'Efficient hybrid Mamba-Transformer MoE with 1M context. Good for long-context agentic reasoning and planning.', 1048576, '561B (Mamba-Transformer MoE)', 'Mamba-Transformer MoE', '["text"]', '["text"]', '["long-context", "reasoning", "agent", "moe"]', '{"function_calling": true, "structured_output": false, "reasoning": true, "thinking": true}', 'fast', '["long-context reasoning", "agentic planning", "code analysis"]', '{"input": 0.0, "output": 0.0}', 0, '', 'reasoning'),
    ('groq', 'llama-3.3-70b-versatile', 'Llama 3.3 70B Versatile', 'Meta''s 70B. Best Groq model — fast (1.3s avg), excellent tool calling, 10/10 benchmark. Default choice.', 128000, '70B', 'Dense Transformer', '["text"]', '["text"]', '["high-quality", "production", "coding", "default"]', '{"function_calling": true, "structured_output": true, "reasoning": false, "thinking": false}', 'fast', '["agentic coding", "complex tasks", "general purpose"]', '{"input": 0.0, "output": 0.0}', 1, '', 'flagship'),
    ('groq', 'llama-3.1-8b-instant', 'Llama 3.1 8B Instant', 'Meta''s 8B. Ultra-fast (1.7s), generous rate limits (14.4K RPD).', 131072, '8B', 'Dense Transformer', '["text"]', '["text"]', '["ultra-fast", "lightweight", "production"]', '{"function_calling": true, "structured_output": true, "reasoning": false, "thinking": false}', 'fast', '["quick responses", "simple coding", "batch processing"]', '{"input": 0.0, "output": 0.0}', 0, '', 'compact'),
    ('groq', 'openai/gpt-oss-20b', 'GPT OSS 20B', 'OpenAI''s open-source 20B. Best value — fast (1.6s) + high quality + clean tool calls. 10/10 benchmark.', 131072, '20B', 'Dense Transformer', '["text"]', '["text"]', '["openai", "production", "coding", "best-value"]', '{"function_calling": true, "structured_output": true, "reasoning": false, "thinking": false}', 'fast', '["general coding", "agentic workflows", "best bang-for-buck"]', '{"input": 0.0, "output": 0.0}', 0, '', 'flagship'),
    ('groq', 'openai/gpt-oss-120b', 'GPT OSS 120B', 'OpenAI''s largest open-source model. Highest quality among GPT OSS (6.2s avg). Best tool calling.', 131072, '120B', 'Dense Transformer', '["text"]', '["text"]', '["openai", "high-quality", "production"]', '{"function_calling": true, "structured_output": true, "reasoning": false, "thinking": false}', 'moderate', '["complex coding", "agentic workflows", "high-quality output"]', '{"input": 0.0, "output": 0.0}', 0, '', 'flagship'),
    ('groq', 'openai/gpt-oss-safeguard-20b', 'Safety GPT OSS 20B', 'OpenAI''s open-source 20B safety-tuned model. Same architecture as GPT OSS 20B with safety guardrails.', 131072, '20B', 'Dense Transformer', '["text"]', '["text"]', '["openai", "production", "safety"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": false}', 'fast', '["general coding", "agentic workflows", "safety-sensitive tasks"]', '{"input": 0.0, "output": 0.0}', 0, '', 'flagship'),
    ('groq', 'groq/compound', 'Compound', 'Groq''s in-house flagship. Ultra-fast inference on LPU.', 131072, 'unknown', 'Dense Transformer', '["text"]', '["text"]', '["production", "fast", "groq"]', '{"function_calling": false, "structured_output": true, "reasoning": false, "thinking": false}', 'fast', '["quick responses", "general purpose", "lightweight"]', '{"input": 0.0, "output": 0.0}', 0, '', 'flagship'),
    ('groq', 'groq/compound-mini', 'Compound Mini', 'Groq''s compact in-house model. Even faster, low-latency responses.', 131072, 'unknown', 'Dense Transformer', '["text"]', '["text"]', '["production", "ultra-fast", "lightweight", "groq"]', '{"function_calling": false, "structured_output": true, "reasoning": false, "thinking": false}', 'fast', '["quick responses", "batch processing", "simple tasks"]', '{"input": 0.0, "output": 0.0}', 0, '', 'compact'),
    ('groq', 'allam-2-7b', 'ALLaM-2-7b', 'SDAIA''s bilingual Arabic/English 7B model. Strong for Arabic-language tasks.', 4096, '7B', 'Dense Transformer', '["text"]', '["text"]', '["production", "bilingual", "arabic"]', '{"function_calling": false, "structured_output": true, "reasoning": false, "thinking": false}', 'fast', '["arabic text", "translation", "quick responses"]', '{"input": 0.0, "output": 0.0}', 0, '', 'compact'),
    ('groq', 'meta-llama/llama-prompt-guard-2-22m', 'Llama Prompt Guard 2 22M', 'Meta''s prompt-injection classifier. Special-purpose, not for general chat.', 512, '22M', 'Dense Transformer', '["text"]', '["text"]', '["safety", "classifier", "special-purpose"]', '{"function_calling": false, "structured_output": false, "reasoning": false, "thinking": false}', 'fast', '["prompt safety", "classification"]', '{"input": 0.0, "output": 0.0}', 0, '', 'compact'),
    ('groq', 'meta-llama/llama-prompt-guard-2-86m', 'Prompt Guard 2 86M', 'Meta''s larger prompt-injection classifier. Special-purpose, not for general chat.', 512, '86M', 'Dense Transformer', '["text"]', '["text"]', '["safety", "classifier", "special-purpose"]', '{"function_calling": false, "structured_output": true, "reasoning": false, "thinking": false}', 'fast', '["prompt safety", "classification"]', '{"input": 0.0, "output": 0.0}', 0, '', 'compact'),
    ('anthropic', 'claude-sonnet-4-20250514', 'Claude Sonnet 4', 'Balanced flagship model. Strong coding, reasoning, and tool use.', 200000, 'unknown', 'Dense Transformer', '["text"]', '["text"]', '["production", "coding", "default"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": true}', 'moderate', '["agentic coding", "complex tasks", "general purpose"]', '{"input": 3.0, "output": 15.0, "cache_read": 0.3, "cache_creation": 3.75}', 1, 'cl100k_base', 'flagship'),
    ('anthropic', 'claude-3-5-haiku-20241022', 'Claude 3.5 Haiku', 'Fast, low-cost model for quick responses and lightweight tasks.', 200000, 'unknown', 'Dense Transformer', '["text"]', '["text"]', '["fast", "lightweight"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": false}', 'fast', '["quick responses", "simple coding", "batch processing"]', '{"input": 0.8, "output": 4.0, "cache_read": 0.08, "cache_creation": 1.0}', 0, 'cl100k_base', 'compact'),
    ('anthropic', 'claude-3-opus-20240229', 'Claude 3 Opus', 'Most capable flagship for the hardest reasoning and writing tasks.', 200000, 'unknown', 'Dense Transformer', '["text"]', '["text"]', '["frontier", "reasoning"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": true}', 'slow', '["complex reasoning", "production code", "analysis"]', '{"input": 15.0, "output": 75.0, "cache_read": 1.5, "cache_creation": 18.75}', 0, 'cl100k_base', 'flagship'),
    ('google', 'gemini-3.5-flash-lite', 'Gemini 3.5 Flash-Lite', 'Lightweight 3.5 Flash. Ultra-fast (1.6s avg), no thinking overhead. 10/10 benchmark. Best speed/quality ratio.', 1048576, 'unknown', 'Dense Transformer', '["text", "image"]', '["text"]', '["ultra-fast", "lightweight", "latest-gen", "default"]', '{"function_calling": true, "structured_output": true, "reasoning": false, "thinking": false}', 'fast', '["quick responses", "simple coding", "batch processing"]', '{"input": 0.075, "output": 0.3, "cache_read": 0.015}', 1, '', 'compact'),
    ('google', 'gemini-3.5-flash', 'Gemini 3.5 Flash', 'Latest generation flash model. Thinking support. Fast with strong reasoning. FC confirmed.', 1048576, 'unknown', 'Dense Transformer', '["text", "image"]', '["text"]', '["fast", "thinking", "latest-gen"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": true}', 'fast', '["general coding", "reasoning", "fast responses"]', '{"input": 0.15, "output": 0.6, "cache_read": 0.03}', 0, '', 'compact'),
    ('google', 'gemini-2.5-pro', 'Gemini 2.5 Pro', 'Google''s most capable model. Advanced reasoning and code generation. 1M context.', 1048576, 'unknown', 'Dense Transformer', '["text", "image", "audio", "video"]', '["text"]', '["frontier", "reasoning", "code", "production"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": true}', 'moderate', '["complex coding", "reasoning tasks", "agentic workflows"]', '{"input": 1.25, "output": 5.0, "cache_read": 0.25}', 0, '', 'flagship'),
    ('google', 'gemini-3.1-pro-preview', 'Gemini 3.1 Pro Preview', 'Latest pro preview. Strongest reasoning and code generation.', 1048576, 'unknown', 'Dense Transformer', '["text", "image"]', '["text"]', '["preview", "frontier", "latest-gen"]', '{"function_calling": true, "structured_output": true, "reasoning": true, "thinking": true}', 'moderate', '["complex coding", "multi-step agentic tasks", "production code"]', '{"input": 1.25, "output": 5.0, "cache_read": 0.25}', 0, '', 'flagship'),
    ('custom', 'llama3', 'Llama 3', 'Local default model for self-hosted / custom endpoints.', 8192, NULL, NULL, '["text"]', '["text"]', '[]', '{"function_calling": true, "structured_output": false, "reasoning": false, "thinking": false}', 'fast', '["local inference", "self-hosted"]', '{"input": 0.0, "output": 0.0}', 1, '', 'compact')
ON CONFLICT(provider_id, id) DO UPDATE SET
    name = excluded.name,
    description = excluded.description,
    context_window = excluded.context_window,
    parameters = excluded.parameters,
    architecture = excluded.architecture,
    input_modalities = excluded.input_modalities,
    output_modalities = excluded.output_modalities,
    tags = excluded.tags,
    model_capabilities_json = excluded.model_capabilities_json,
    speed_tier = excluded.speed_tier,
    best_for = excluded.best_for,
    pricing_json = excluded.pricing_json,
    is_default = excluded.is_default,
    tokenizer = excluded.tokenizer,
    prompt_tier = excluded.prompt_tier
;
