import { Scenario } from '../../../types/scenario';

let idCounter = 0;
const uid = () => `evt_${++idCounter}`;

export const buildScenario = (prompt: string): Scenario => ({
  id: `build_${Date.now()}`,
  mode: 'build',
  prompt,
  events: [
    {
      kind: 'thinking',
      id: uid(),
      thoughts: [
        { text: 'Understanding the request', delay: 300 },
        { text: 'Choosing FastAPI project structure', delay: 400 },
        { text: 'Planning folders and modules', delay: 350 },
        { text: 'Determining required files', delay: 300 },
        { text: 'Designing CRUD endpoints', delay: 400 },
        { text: 'Considering dependencies', delay: 300 },
      ],
      duration: 2200,
    },
    {
      kind: 'file_create',
      id: uid(),
      filePath: 'backend/app/__init__.py',
      directory: 'backend/app/',
      language: 'python',
      lines: [
        { text: '# Zenith Generated Application', type: 'add' },
        { text: 'from fastapi import FastAPI', type: 'add' },
        { text: '', type: 'add' },
        { text: 'app = FastAPI(title="User CRUD API")', type: 'add' },
      ],
    },
    {
      kind: 'file_create',
      id: uid(),
      filePath: 'backend/app/models.py',
      directory: 'backend/app/',
      language: 'python',
      lines: [
        { text: 'from pydantic import BaseModel', type: 'add' },
        { text: 'from typing import Optional', type: 'add' },
        { text: '', type: 'add' },
        { text: 'class User(BaseModel):', type: 'add' },
        { text: '    id: Optional[int] = None', type: 'add' },
        { text: '    name: str', type: 'add' },
        { text: '    email: str', type: 'add' },
      ],
    },
    {
      kind: 'file_create',
      id: uid(),
      filePath: 'backend/app/api/users.py',
      directory: 'backend/app/api/',
      language: 'python',
      lines: [
        { text: 'from fastapi import APIRouter, HTTPException', type: 'add' },
        { text: 'from ..models import User', type: 'add' },
        { text: '', type: 'add' },
        { text: 'router = APIRouter()', type: 'add' },
        { text: 'users_db: list[User] = []', type: 'add' },
        { text: '', type: 'add' },
        { text: '@router.get("/users")', type: 'add' },
        { text: 'async def get_users():', type: 'add' },
        { text: '    return users_db', type: 'add' },
        { text: '', type: 'add' },
        { text: '@router.post("/users")', type: 'add' },
        { text: 'async def create_user(user: User):', type: 'add' },
        { text: '    user.id = len(users_db) + 1', type: 'add' },
        { text: '    users_db.append(user)', type: 'add' },
        { text: '    return user', type: 'add' },
      ],
    },
    {
      kind: 'file_create',
      id: uid(),
      filePath: 'backend/app/api/__init__.py',
      directory: 'backend/app/api/',
      language: 'python',
      lines: [
        { text: 'from .users import router as users_router', type: 'add' },
      ],
    },
    {
      kind: 'file_create',
      id: uid(),
      filePath: 'backend/main.py',
      directory: 'backend/',
      language: 'python',
      lines: [
        { text: 'from app import app', type: 'add' },
        { text: 'from app.api.users import router', type: 'add' },
        { text: '', type: 'add' },
        { text: 'app.include_router(router)', type: 'add' },
      ],
    },
    {
      kind: 'file_create',
      id: uid(),
      filePath: 'backend/requirements.txt',
      directory: 'backend/',
      language: 'text',
      lines: [
        { text: 'fastapi>=0.115.0', type: 'add' },
        { text: 'uvicorn>=0.30.0', type: 'add' },
      ],
    },
    {
      kind: 'thinking',
      id: uid(),
      thoughts: [
        { text: 'Project files are ready', delay: 300 },
        { text: 'Validating imports', delay: 400 },
        { text: 'Registering routes', delay: 300 },
        { text: 'Installing dependencies', delay: 350 },
        { text: 'Running application', delay: 400 },
        { text: 'Verifying startup', delay: 300 },
      ],
      duration: 1800,
    },
    {
      kind: 'terminal',
      id: uid(),
      command: 'pip install -r requirements.txt',
      output: [
        'Collecting fastapi',
        '  Downloading fastapi-0.115.0-py3-none-any.whl (95 kB)',
        'Collecting uvicorn',
        '  Downloading uvicorn-0.30.0-py3-none-any.whl',
        'Installing collected packages: fastapi, uvicorn',
        'Successfully installed fastapi-0.115.0 uvicorn-0.30.0',
      ],
      duration: 2800,
    },
    {
      kind: 'error',
      id: uid(),
      message: "ModuleNotFoundError: No module named 'app.api.users'",
      command: 'uvicorn backend.main:app --reload',
      stack: '  File "backend/main.py", line 2, in <module>\n    from app.api.users import router\nModuleNotFoundError: No module named \'app.api.users\'',
    },
    {
      kind: 'thinking',
      id: uid(),
      thoughts: [
        { text: 'The router was not exported correctly', delay: 300 },
        { text: 'Updating __init__.py exports', delay: 350 },
        { text: 'Fixing import path in main.py', delay: 300 },
        { text: 'Retrying...', delay: 250 },
      ],
      duration: 1200,
    },
    {
      kind: 'file_edit',
      id: uid(),
      filePath: 'backend/main.py',
      directory: 'backend/',
      language: 'python',
      removedLines: [
        { text: 'from app import app', type: 'context' },
        { text: 'from app.api.users import router', type: 'context' },
      ],
      addedLines: [
        { text: 'from app import app', type: 'context' },
        { text: 'from app.api.users import router', type: 'add' },
        { text: 'import sys', type: 'add' },
        { text: 'sys.path.insert(0, "backend")', type: 'add' },
      ],
    },
    {
      kind: 'retry',
      id: uid(),
      message: 'Retrying server startup',
      attempt: 2,
    },
    {
      kind: 'terminal',
      id: uid(),
      command: 'uvicorn backend.main:app --reload',
      output: [
        'INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)',
        'INFO:     Started reloader process [28456]',
        'INFO:     Started server process [28460]',
        'INFO:     Waiting for application startup.',
        'INFO:     Application startup complete.',
      ],
      duration: 2400,
    },
    {
      kind: 'success',
      id: uid(),
      message: 'Application started successfully on http://127.0.0.1:8000',
      filesCreated: [
        'backend/app/__init__.py',
        'backend/app/models.py',
        'backend/app/api/__init__.py',
        'backend/app/api/users.py',
        'backend/main.py',
        'backend/requirements.txt',
      ],
      commandsExecuted: [
        'pip install -r requirements.txt',
        'uvicorn backend.main:app --reload',
      ],
    },
    {
      kind: 'summary',
      id: uid(),
      title: 'FastAPI Project Created',
      description: 'Successfully created a FastAPI project with User CRUD endpoints. The application starts correctly and all routes have been registered.',
      filesCreated: [
        'backend/app/__init__.py',
        'backend/app/models.py',
        'backend/app/api/__init__.py',
        'backend/app/api/users.py',
        'backend/main.py',
        'backend/requirements.txt',
      ],
      commandsExecuted: [
        'pip install -r requirements.txt',
        'uvicorn backend.main:app --reload',
      ],
      verified: [
        'FastAPI app initialization',
        'Pydantic models',
        'CRUD route handlers',
        'Module imports',
        'Server startup',
      ],
    },
  ],
});
