import { Scenario } from '../../../types/scenario';

let idCounter = 0;
const uid = () => `ci_${++idCounter}`;

export const cicdScenario = (prompt: string): Scenario => ({
  id: `cicd_${Date.now()}`,
  mode: 'build',
  prompt,
  events: [
    {
      kind: 'thinking',
      id: uid(),
      thoughts: [
        { text: 'Analyzing repository structure', delay: 300 },
        { text: 'Determining CI/CD requirements', delay: 350 },
        { text: 'Designing pipeline stages', delay: 400 },
        { text: 'Configuring environment secrets', delay: 300 },
      ],
      duration: 1500,
    },
    {
      kind: 'file_create',
      id: uid(),
      filePath: '.github/workflows/ci.yml',
      directory: '.github/workflows/',
      language: 'yaml',
      lines: [
        { text: 'name: CI/CD Pipeline', type: 'add' },
        { text: '', type: 'add' },
        { text: 'on:', type: 'add' },
        { text: '  push:', type: 'add' },
        { text: '    branches: [main, develop]', type: 'add' },
        { text: '  pull_request:', type: 'add' },
        { text: '    branches: [main]', type: 'add' },
        { text: '', type: 'add' },
        { text: 'jobs:', type: 'add' },
        { text: '  test:', type: 'add' },
        { text: '    runs-on: ubuntu-latest', type: 'add' },
        { text: '    steps:', type: 'add' },
        { text: '      - uses: actions/checkout@v4', type: 'add' },
        { text: '      - uses: actions/setup-node@v4', type: 'add' },
        { text: '        with:', type: 'add' },
        { text: '          node-version: 20', type: 'add' },
        { text: '          cache: npm', type: 'add' },
        { text: '      - run: npm ci', type: 'add' },
        { text: '      - run: npm run lint', type: 'add' },
        { text: '      - run: npm test -- --coverage', type: 'add' },
        { text: '      - run: npm run build', type: 'add' },
        { text: '', type: 'add' },
        { text: '  deploy:', type: 'add' },
        { text: '    needs: test', type: 'add' },
        { text: '    if: github.ref == refs/heads/main', type: 'add' },
        { text: '    runs-on: ubuntu-latest', type: 'add' },
        { text: '    steps:', type: 'add' },
        { text: '      - uses: actions/checkout@v4', type: 'add' },
        { text: '      - run: docker build -t app .', type: 'add' },
        { text: '      - run: docker push registry/app:latest', type: 'add' },
      ],
    },
    {
      kind: 'file_create',
      id: uid(),
      filePath: '.github/workflows/cd.yml',
      directory: '.github/workflows/',
      language: 'yaml',
      lines: [
        { text: 'name: Deploy to Production', type: 'add' },
        { text: '', type: 'add' },
        { text: 'on:', type: 'add' },
        { text: '  workflow_run:', type: 'add' },
        { text: '    workflows: ["CI/CD Pipeline"]', type: 'add' },
        { text: '    types: [completed]', type: 'add' },
        { text: '', type: 'add' },
        { text: 'jobs:', type: 'add' },
        { text: '  deploy-staging:', type: 'add' },
        { text: '    if: ${{ github.event.workflow_run.conclusion == success }}', type: 'add' },
        { text: '    runs-on: ubuntu-latest', type: 'add' },
        { text: '    environment: staging', type: 'add' },
        { text: '    steps:', type: 'add' },
        { text: '      - run: echo "Deploying to staging..."', type: 'add' },
        { text: '      - run: kubectl apply -f k8s/staging/', type: 'add' },
      ],
    },
    {
      kind: 'thinking',
      id: uid(),
      thoughts: [
        { text: 'Validating YAML syntax', delay: 300 },
        { text: 'Checking workflow triggers', delay: 350 },
        { text: 'Testing pipeline locally', delay: 400 },
      ],
      duration: 1100,
    },
    {
      kind: 'terminal',
      id: uid(),
      command: 'act -l',
      output: [
        'Stage  Name                          Workflow file  Trigger event',
        'test    CI/CD Pipeline               ci.yml         push, pull_request',
        'deploy  CI/CD Pipeline               ci.yml         push (main only)',
      ],
      duration: 1500,
    },
    {
      kind: 'warning',
      id: uid(),
      message: 'GitHub Actions secrets not configured for this repository',
      details: 'Set DEPLOY_TOKEN, REGISTRY_URL, and KUBE_CONFIG in repository settings before first deployment.',
    },
    {
      kind: 'summary',
      id: uid(),
      title: 'CI/CD Pipeline Configured',
      description: 'GitHub Actions workflows with test, build, and deploy stages. Includes Docker image building and Kubernetes deployment.',
      filesCreated: [
        '.github/workflows/ci.yml',
        '.github/workflows/cd.yml',
      ],
      commandsExecuted: [
        'act -l',
      ],
      verified: [
        'YAML syntax',
        'Workflow triggers',
        'Job dependencies',
        'Environment configuration',
      ],
    },
  ],
});
