import type { Scenario } from '../../../types/scenario';
import { createScenario, type ScenarioTemplate } from '../templateLoader';

const template: ScenarioTemplate = {
  mode: 'build',
  events: [
    {
      kind: 'thinking',
      thoughts: [
        { text: 'Inspecting workspace repository layout & GitHub Actions workflow syntax rules...', delay: 250 },
        {
          text: 'Evaluating CI matrix strategy (Node 18, 20, 22), pnpm/npm dependency caching, and parallelism',
          delay: 300,
        },
        {
          text: 'Architecting 3-phase CI/CD workflow: Lint & TypeCheck → Parallel Vitest Matrix → Docker Build & Helm Push',
          delay: 350,
        },
        { text: 'Validating local workflow test with nektos/act runner and GitHub OIDC token permissions', delay: 300 },
      ],
      duration: 1500,
    },
    {
      kind: 'file_create',
      filePath: '.github/workflows/ci.yml',
      directory: '.github/workflows/',
      language: 'yaml',
      lines: [
        { text: 'name: Production CI/CD Pipeline', type: 'add' },
        { text: 'on:', type: 'add' },
        { text: '  push:', type: 'add' },
        { text: '    branches: [main, release/*]', type: 'add' },
        { text: '  pull_request:', type: 'add' },
        { text: '    branches: [main]', type: 'add' },
        { text: '', type: 'add' },
        { text: 'permissions:', type: 'add' },
        { text: '  contents: read', type: 'add' },
        { text: '  id-token: write', type: 'add' },
        { text: '  security-events: write', type: 'add' },
        { text: '', type: 'add' },
        { text: 'jobs:', type: 'add' },
        { text: '  lint-and-typecheck:', type: 'add' },
        { text: '    runs-on: ubuntu-latest', type: 'add' },
        { text: '    steps:', type: 'add' },
        { text: '      - uses: actions/checkout@v4', type: 'add' },
        { text: '      - uses: actions/setup-node@v4', type: 'add' },
        { text: '        with:', type: 'add' },
        { text: '          node-version: 22', type: 'add' },
        { text: '          cache: npm', type: 'add' },
        { text: '      - run: npm ci', type: 'add' },
        { text: '      - run: npm run typecheck', type: 'add' },
        { text: '      - run: npm run lint', type: 'add' },
        { text: '', type: 'add' },
        { text: '  test-matrix:', type: 'add' },
        { text: '    needs: lint-and-typecheck', type: 'add' },
        { text: '    runs-on: ubuntu-latest', type: 'add' },
        { text: '    strategy:', type: 'add' },
        { text: '      matrix:', type: 'add' },
        { text: '        node: [18, 20, 22]', type: 'add' },
        { text: '    steps:', type: 'add' },
        { text: '      - uses: actions/checkout@v4', type: 'add' },
        { text: '      - uses: actions/setup-node@v4', type: 'add' },
        { text: '        with:', type: 'add' },
        { text: '          node-version: ${{ matrix.node }}', type: 'add' },
        { text: '          cache: npm', type: 'add' },
        { text: '      - run: npm ci', type: 'add' },
        { text: '      - run: npm test -- --coverage', type: 'add' },
      ],
    },
    {
      kind: 'build_step',
      step: 'Local CI Workflow Simulation ($ act -j lint-and-typecheck)',
      status: 'success',
      duration: 1200,
      output: [
        'Parsing .github/workflows/ci.yml using nektos/act...',
        'Running job: lint-and-typecheck...',
        '✓ Step actions/checkout@v4 complete',
        '✓ Step actions/setup-node@v4 (node-version: 22) complete',
        '✓ Step npm run typecheck complete (0 errors)',
        '✓ Job lint-and-typecheck completed successfully in 3.4s',
      ],
    },
    {
      kind: 'test_execution',
      command: 'act -j test-matrix',
      framework: 'GitHub Actions Matrix (Node 18, 20, 22)',
      summary: { total: 3, passed: 3, failed: 0, skipped: 0 },
      results: [
        { name: 'Matrix runner Node 18.x -> Vitest suite (39 passed)', status: 'pass', duration: 1800 },
        { name: 'Matrix runner Node 20.x -> Vitest suite (39 passed)', status: 'pass', duration: 1720 },
        { name: 'Matrix runner Node 22.x -> Vitest suite (39 passed)', status: 'pass', duration: 1650 },
      ],
    },
    {
      kind: 'summary',
      title: 'GitHub Actions CI/CD Pipeline Assembled & Verified',
      description:
        'Created 3-stage GitHub Actions CI/CD workflow with Node 18/20/22 testing matrix, OIDC token permissions, dependency caching, and act local verification.',
      filesCreated: ['.github/workflows/ci.yml'],
      commandsExecuted: ['act -j lint-and-typecheck', 'act -j test-matrix'],
      verified: [
        'GitHub Actions Workflow Syntax Validation',
        'OIDC Permissions & Least Privilege Security Scope',
        'Matrix Build Parallel Execution (Node 18, 20, 22)',
        'Act Local Runner Verification (All 3 jobs passed)',
      ],
    },
  ],
};

export const cicdScenario = (prompt: string): Scenario => createScenario(prompt, template);
