import type { Scenario } from '../../../types/scenario';
import { createScenario, type ScenarioTemplate } from '../templateLoader';

const template: ScenarioTemplate = {
  mode: 'build',
  events: [
    {
      kind: 'thinking',
      thoughts: [
        { text: 'Analyzing project structure for containerization', delay: 300 },
        { text: 'Identifying Node.js runtime dependencies & Nginx static serving requirements', delay: 350 },
        { text: 'Planning multi-stage image build & layer caching strategy', delay: 400 },
        { text: 'Configuring Docker container health checks and bridge networking', delay: 300 },
      ],
      duration: 1500,
    },
    {
      kind: 'file_create',
      filePath: 'Dockerfile',
      directory: './',
      language: 'dockerfile',
      lines: [
        { text: '# Stage 1: Build', type: 'add' },
        { text: 'FROM node:20-alpine AS builder', type: 'add' },
        { text: 'WORKDIR /app', type: 'add' },
        { text: 'COPY package*.json ./', type: 'add' },
        { text: 'RUN npm ci --only=production', type: 'add' },
        { text: 'COPY . .', type: 'add' },
        { text: 'RUN npm run build', type: 'add' },
        { text: '', type: 'add' },
        { text: '# Stage 2: Production', type: 'add' },
        { text: 'FROM nginx:alpine AS production', type: 'add' },
        { text: 'COPY --from=builder /app/dist /usr/share/nginx/html', type: 'add' },
        { text: 'COPY nginx.conf /etc/nginx/conf.d/default.conf', type: 'add' },
        { text: 'EXPOSE 80', type: 'add' },
        { text: 'HEALTHCHECK CMD curl -f http://localhost/ || exit 1', type: 'add' },
        { text: 'CMD ["nginx", "-g", "daemon off;"]', type: 'add' },
      ],
    },
    {
      kind: 'file_create',
      filePath: 'docker-compose.yml',
      directory: './',
      language: 'yaml',
      lines: [
        { text: 'version: "3.8"', type: 'add' },
        { text: 'services:', type: 'add' },
        { text: '  app:', type: 'add' },
        { text: '    build: .', type: 'add' },
        { text: '    ports:', type: 'add' },
        { text: '      - "3000:80"', type: 'add' },
        { text: '    environment:', type: 'add' },
        { text: '      - NODE_ENV=production', type: 'add' },
        { text: '    restart: unless-stopped', type: 'add' },
        { text: '    healthcheck:', type: 'add' },
        { text: '      test: ["CMD", "curl", "-f", "http://localhost/"]', type: 'add' },
        { text: '      interval: 30s', type: 'add' },
        { text: '      timeout: 10s', type: 'add' },
        { text: '      retries: 3', type: 'add' },
      ],
    },
    {
      kind: 'file_create',
      filePath: '.dockerignore',
      directory: './',
      language: 'text',
      lines: [
        { text: 'node_modules', type: 'add' },
        { text: 'dist', type: 'add' },
        { text: '.git', type: 'add' },
        { text: '*.md', type: 'add' },
        { text: '.env*', type: 'add' },
      ],
    },
    {
      kind: 'thinking',
      thoughts: [
        { text: 'Building Docker image layer cache', delay: 300 },
        { text: 'Testing container startup & port forwarding', delay: 400 },
        { text: 'Verifying Nginx health check endpoint', delay: 300 },
      ],
      duration: 1000,
    },
    {
      kind: 'build_step',
      step: 'docker build -t app:latest .',
      status: 'success',
      duration: 3800,
      output: [
        '[+] Building 18.4s (12/12) FINISHED',
        ' => [builder 1/5] FROM node:20-alpine',
        ' => [builder 2/5] COPY package*.json ./',
        ' => [builder 3/5] RUN npm ci --only=production',
        ' => [builder 4/5] COPY . .',
        ' => [builder 5/5] RUN npm run build',
        ' => [production 1/3] FROM nginx:alpine',
        ' => [production 2/3] COPY --from=builder /app/dist',
        ' => exporting to image docker.io/library/app:latest',
      ],
    },
    {
      kind: 'terminal',
      command: 'docker compose up -d',
      output: [
        '[+] Running 1/1',
        ' ✔ app Started',
        'app_1  | 172.17.0.1 - - [22/Jul/2026:10:00:00 +0000] "GET / HTTP/1.1" 200',
      ],
      duration: 2000,
    },
    {
      kind: 'deployment',
      target: 'Local Docker Desktop Container',
      status: 'success',
      url: 'http://localhost:3000',
      output: ['Container ID: 7f89d0e12a4b', 'Port Mapping: 0.0.0.0:3000->80/tcp', 'Health Status: Healthy'],
    },
    {
      kind: 'summary',
      title: 'Docker Configuration Complete',
      description: 'Multi-stage Docker build with production-ready Nginx serving and docker-compose orchestration.',
      filesCreated: ['Dockerfile', 'docker-compose.yml', '.dockerignore'],
      commandsExecuted: ['docker build -t app:latest .', 'docker compose up -d'],
      verified: [
        'Multi-stage layer caching',
        'Health check endpoint (http://localhost:3000)',
        'Production Nginx configuration',
        'Container startup & deployment',
      ],
    },
  ],
};

export const dockerScenario = (prompt: string): Scenario => createScenario(prompt, template);
