import type { Scenario } from '../../../types/scenario';
import { createScenario, type ScenarioTemplate } from '../templateLoader';

const template: ScenarioTemplate = {
  mode: 'build',
  events: [
    {
      kind: 'thinking',
      thoughts: [
        { text: 'Setting up React 19 project with Vite', delay: 300 },
        { text: 'Configuring TypeScript and ESLint rules', delay: 350 },
        { text: 'Planning responsive component architecture & layout', delay: 400 },
        { text: 'Integrating Recharts analytics & Zustand state management', delay: 300 },
      ],
      duration: 1500,
    },
    {
      kind: 'terminal',
      command: 'npm create vite@latest dashboard -- --template react-ts',
      output: ['Scaffolding project in ./dashboard...', '✓ Scaffolding complete.'],
      duration: 1200,
    },
    {
      kind: 'terminal',
      command: 'npm install recharts@2 react-router-dom@7 zustand@5 lucide-react',
      output: ['added 42 packages in 2.8s', 'found 0 vulnerabilities'],
      duration: 2000,
    },
    {
      kind: 'file_create',
      filePath: 'dashboard/src/App.tsx',
      directory: 'dashboard/src/',
      language: 'tsx',
      lines: [
        { text: 'import { BrowserRouter, Routes, Route } from "react-router-dom";', type: 'add' },
        { text: 'import { DashboardLayout } from "./layouts/DashboardLayout";', type: 'add' },
        { text: 'import { OverviewPage } from "./pages/OverviewPage";', type: 'add' },
        { text: 'import { AnalyticsPage } from "./pages/AnalyticsPage";', type: 'add' },
        { text: '', type: 'add' },
        { text: 'export function App() {', type: 'add' },
        { text: '  return (', type: 'add' },
        { text: '    <BrowserRouter>', type: 'add' },
        { text: '      <Routes>', type: 'add' },
        { text: '        <Route element={<DashboardLayout />}>', type: 'add' },
        { text: '          <Route path="/" element={<OverviewPage />} />', type: 'add' },
        { text: '          <Route path="/analytics" element={<AnalyticsPage />} />', type: 'add' },
        { text: '        </Route>', type: 'add' },
        { text: '      </Routes>', type: 'add' },
        { text: '    </BrowserRouter>', type: 'add' },
        { text: '  );', type: 'add' },
        { text: '}', type: 'add' },
      ],
    },
    {
      kind: 'file_create',
      filePath: 'dashboard/src/components/MetricCard.tsx',
      directory: 'dashboard/src/components/',
      language: 'tsx',
      lines: [
        { text: 'interface MetricCardProps {', type: 'add' },
        { text: '  title: string;', type: 'add' },
        { text: '  value: string | number;', type: 'add' },
        { text: '  change?: number;', type: 'add' },
        { text: '  icon: string;', type: 'add' },
        { text: '}', type: 'add' },
        { text: '', type: 'add' },
        { text: 'export function MetricCard({ title, value, change, icon }: MetricCardProps) {', type: 'add' },
        { text: '  return (', type: 'add' },
        { text: '    <div className="metric-card">', type: 'add' },
        { text: '      <div className="metric-icon">{icon}</div>', type: 'add' },
        { text: '      <div className="metric-value">{value}</div>', type: 'add' },
        { text: '      <div className="metric-title">{title}</div>', type: 'add' },
        { text: '      {change !== undefined && (', type: 'add' },
        { text: '        <div className={`metric-change ${change >= 0 ? "positive" : "negative"}`}>', type: 'add' },
        { text: '          {change >= 0 ? "+" : ""}{change}%', type: 'add' },
        { text: '        </div>', type: 'add' },
        { text: '      )}', type: 'add' },
        { text: '    </div>', type: 'add' },
        { text: '  );', type: 'add' },
        { text: '}', type: 'add' },
      ],
    },
    {
      kind: 'file_create',
      filePath: 'dashboard/src/pages/OverviewPage.tsx',
      directory: 'dashboard/src/pages/',
      language: 'tsx',
      lines: [
        { text: 'import { MetricCard } from "../components/MetricCard";', type: 'add' },
        { text: 'import { BarChart, Bar, XAxis, YAxis, Tooltip } from "recharts";', type: 'add' },
        { text: '', type: 'add' },
        { text: 'const data = [', type: 'add' },
        { text: '  { name: "Jan", revenue: 4000, users: 2400 },', type: 'add' },
        { text: '  { name: "Feb", revenue: 3000, users: 1398 },', type: 'add' },
        { text: '  { name: "Mar", revenue: 5000, users: 3800 },', type: 'add' },
        { text: '];', type: 'add' },
        { text: '', type: 'add' },
        { text: 'export function OverviewPage() {', type: 'add' },
        { text: '  return (', type: 'add' },
        { text: '    <div className="overview">', type: 'add' },
        { text: '      <MetricCard title="Total Revenue" value="$12,000" change={12.5} icon="$" />', type: 'add' },
        { text: '      <MetricCard title="Active Users" value="7,598" change={8.2} icon="U" />', type: 'add' },
        { text: '      <BarChart width={600} height={300} data={data}>', type: 'add' },
        { text: '        <XAxis dataKey="name" />', type: 'add' },
        { text: '        <YAxis />', type: 'add' },
        { text: '        <Tooltip />', type: 'add' },
        { text: '        <Bar dataKey="revenue" fill="#10b981" />', type: 'add' },
        { text: '      </BarChart>', type: 'add' },
        { text: '    </div>', type: 'add' },
        { text: '  );', type: 'add' },
        { text: '}', type: 'add' },
      ],
    },
    {
      kind: 'thinking',
      thoughts: [
        { text: 'Running Vitest unit test suite on dashboard components', delay: 300 },
        { text: 'Executing TypeScript compiler dry-run', delay: 350 },
      ],
      duration: 1000,
    },
    {
      kind: 'test_execution',
      command: 'npx vitest run',
      framework: 'Vitest 1.6',
      results: [
        { name: 'MetricCard renders title and formatted value correctly', status: 'pass', duration: 42 },
        { name: 'OverviewPage renders Recharts revenue visualization', status: 'pass', duration: 118 },
        { name: 'App routing resolves overview and analytics routes', status: 'pass', duration: 65 },
      ],
      summary: { total: 3, passed: 3, failed: 0, skipped: 0 },
    },
    {
      kind: 'build_step',
      step: 'npx tsc --noEmit',
      status: 'success',
      duration: 1400,
      output: ['✓ TypeScript type checking passed cleanly.'],
    },
    {
      kind: 'terminal',
      command: 'npm run build',
      output: [
        'vite v6.0.0 building for production...',
        '✓ 23 modules transformed.',
        'dist/index.html                   0.46 kB │ gzip:  0.30 kB',
        'dist/assets/index-Cv3xY1qJ.js   142.85 kB │ gzip: 45.72 kB',
        '✓ built in 1.84s',
      ],
      duration: 2200,
    },
    {
      kind: 'summary',
      title: 'React 19 Dashboard Created',
      description:
        'A responsive React 19 dashboard featuring Recharts data visualizations, Zustand state management, and Vitest test coverage.',
      filesCreated: [
        'dashboard/src/App.tsx',
        'dashboard/src/components/MetricCard.tsx',
        'dashboard/src/pages/OverviewPage.tsx',
      ],
      commandsExecuted: [
        'npm create vite@latest',
        'npm install recharts react-router-dom zustand',
        'npx vitest run',
        'npm run build',
      ],
      verified: ['TypeScript compilation', 'Vitest component test suite (3 passed)', 'Production bundle optimization'],
    },
  ],
};

export const reactDashboardScenario = (prompt: string): Scenario => createScenario(prompt, template);
