import type { Scenario } from '../../../types/scenario';
import { createScenario, type ScenarioTemplate } from '../templateLoader';

const template: ScenarioTemplate = {
  mode: 'build',
  events: [
    {
      kind: 'thinking',
      thoughts: [
        { text: 'Inspecting workspace structure and parsing package.json / tsconfig.json dependencies...', delay: 250 },
        {
          text: 'Evaluating React 19 concurrent features, useActionState, useOptimistic, and Zustand v5 state store contracts',
          delay: 300,
        },
        {
          text: 'Architecting zero-re-render component hierarchy with dynamic code splitting for Recharts analytics engine',
          delay: 350,
        },
        {
          text: 'Formulating strict TypeScript interfaces, responsive CSS Grid layout tokens, and accessibility (a11y) ARIA roles',
          delay: 300,
        },
        {
          text: 'Validating Vitest test runner configuration, React Testing Library hooks, and Biome linter constraints',
          delay: 250,
        },
      ],
      duration: 1600,
    },
    {
      kind: 'terminal',
      command: 'npx create-vite@latest dashboard --template react-ts --no-interactive',
      output: [
        'Scaffolding React 19 + TypeScript enterprise template in ./dashboard...',
        'Creating package.json, tsconfig.json, vite.config.ts, index.html...',
        '✓ Project scaffolded cleanly in 1.4s',
      ],
      duration: 1400,
    },
    {
      kind: 'terminal',
      command:
        'npm install recharts@^2.12.0 react-router-dom@^7.0.0 zustand@^5.0.0 @tanstack/react-query@^5.0.0 lucide-react',
      output: [
        'Fetch metadata: 5 packages indexed from npm registry',
        'Resolving dependencies: recharts, react-router-dom, zustand, @tanstack/react-query',
        'added 46 packages in 2.91s',
        '✓ 0 security vulnerabilities (checked 46 packages)',
      ],
      duration: 2100,
    },
    {
      kind: 'file_create',
      filePath: 'dashboard/src/store/useDashboardStore.ts',
      directory: 'dashboard/src/store/',
      language: 'ts',
      lines: [
        { text: 'import { create } from "zustand";', type: 'add' },
        { text: 'import { devtools, persist } from "zustand/middleware";', type: 'add' },
        { text: '', type: 'add' },
        { text: 'export interface MetricPoint {', type: 'add' },
        { text: '  timestamp: string;', type: 'add' },
        { text: '  revenue: number;', type: 'add' },
        { text: '  activeUsers: number;', type: 'add' },
        { text: '  conversionRate: number;', type: 'add' },
        { text: '}', type: 'add' },
        { text: '', type: 'add' },
        { text: 'interface DashboardState {', type: 'add' },
        { text: '  timeframe: "24h" | "7d" | "30d" | "1y";', type: 'add' },
        { text: '  metrics: MetricPoint[];', type: 'add' },
        { text: '  setTimeframe: (tf: "24h" | "7d" | "30d" | "1y") => void;', type: 'add' },
        { text: '  fetchRealtimeMetrics: () => Promise<void>;', type: 'add' },
        { text: '}', type: 'add' },
        { text: '', type: 'add' },
        { text: 'export const useDashboardStore = create<DashboardState>()(', type: 'add' },
        { text: '  devtools(', type: 'add' },
        { text: '    persist(', type: 'add' },
        { text: '      (set) => ({', type: 'add' },
        { text: '        timeframe: "7d",', type: 'add' },
        { text: '        metrics: [', type: 'add' },
        {
          text: '          { timestamp: "Mon", revenue: 14200, activeUsers: 2840, conversionRate: 3.8 },',
          type: 'add',
        },
        {
          text: '          { timestamp: "Tue", revenue: 18900, activeUsers: 3410, conversionRate: 4.2 },',
          type: 'add',
        },
        {
          text: '          { timestamp: "Wed", revenue: 21500, activeUsers: 3890, conversionRate: 4.5 },',
          type: 'add',
        },
        {
          text: '          { timestamp: "Thu", revenue: 24800, activeUsers: 4200, conversionRate: 4.9 },',
          type: 'add',
        },
        {
          text: '          { timestamp: "Fri", revenue: 31200, activeUsers: 5100, conversionRate: 5.4 },',
          type: 'add',
        },
        { text: '        ],', type: 'add' },
        { text: '        setTimeframe: (timeframe) => set({ timeframe }),', type: 'add' },
        { text: '        fetchRealtimeMetrics: async () => {', type: 'add' },
        { text: '          // Async realtime WebSocket/SSE ingestion payload', type: 'add' },
        { text: '        },', type: 'add' },
        { text: '      }),', type: 'add' },
        { text: '      { name: "zenith_dashboard_store" }', type: 'add' },
        { text: '    )', type: 'add' },
        { text: '  )', type: 'add' },
        { text: ');', type: 'add' },
      ],
    },
    {
      kind: 'file_create',
      filePath: 'dashboard/src/components/MetricCard.tsx',
      directory: 'dashboard/src/components/',
      language: 'tsx',
      lines: [
        { text: 'import React, { memo } from "react";', type: 'add' },
        { text: 'import { TrendingUp, TrendingDown } from "lucide-react";', type: 'add' },
        { text: '', type: 'add' },
        { text: 'interface MetricCardProps {', type: 'add' },
        { text: '  title: string;', type: 'add' },
        { text: '  value: string;', type: 'add' },
        { text: '  change: string;', type: 'add' },
        { text: '  isPositive: boolean;', type: 'add' },
        { text: '  badge: string;', type: 'add' },
        { text: '}', type: 'add' },
        { text: '', type: 'add' },
        { text: 'export const MetricCard: React.FC<MetricCardProps> = memo(({', type: 'add' },
        { text: '  title, value, change, isPositive, badge', type: 'add' },
        { text: '}) => (', type: 'add' },
        {
          text: '  <div className="rounded-xl border border-zinc-800 bg-zinc-900/60 p-6 backdrop-blur-md">',
          type: 'add',
        },
        { text: '    <div className="flex items-center justify-between">', type: 'add' },
        {
          text: '      <span className="text-xs font-semibold uppercase tracking-wider text-zinc-400">{title}</span>',
          type: 'add',
        },
        {
          text: '      <span className="rounded-md bg-zinc-800/80 px-2 py-1 text-xs font-medium text-emerald-400">{badge}</span>',
          type: 'add',
        },
        { text: '    </div>', type: 'add' },
        { text: '    <div className="mt-4 flex items-baseline justify-between">', type: 'add' },
        { text: '      <h3 className="text-3xl font-extrabold text-zinc-100">{value}</h3>', type: 'add' },
        {
          text: '      <div className={`flex items-center text-sm font-bold ${isPositive ? "text-emerald-400" : "text-rose-400"}`}>',
          type: 'add',
        },
        {
          text: '        {isPositive ? <TrendingUp className="mr-1 h-4 w-4" /> : <TrendingDown className="mr-1 h-4 w-4" />}',
          type: 'add',
        },
        { text: '        {change}', type: 'add' },
        { text: '      </div>', type: 'add' },
        { text: '    </div>', type: 'add' },
        { text: '  </div>', type: 'add' },
        { text: '));', type: 'add' },
      ],
    },
    {
      kind: 'file_create',
      filePath: 'dashboard/src/App.tsx',
      directory: 'dashboard/src/',
      language: 'tsx',
      lines: [
        { text: 'import React, { Suspense, lazy } from "react";', type: 'add' },
        { text: 'import { BrowserRouter, Routes, Route } from "react-router-dom";', type: 'add' },
        { text: 'import { MetricCard } from "./components/MetricCard";', type: 'add' },
        { text: 'import { useDashboardStore } from "./store/useDashboardStore";', type: 'add' },
        { text: '', type: 'add' },
        { text: 'const AnalyticsChart = lazy(() => import("./components/AnalyticsChart"));', type: 'add' },
        { text: '', type: 'add' },
        { text: 'export function App() {', type: 'add' },
        { text: '  const metrics = useDashboardStore((s) => s.metrics);', type: 'add' },
        { text: '  const latest = metrics[metrics.length - 1];', type: 'add' },
        { text: '', type: 'add' },
        { text: '  return (', type: 'add' },
        { text: '    <div className="min-h-screen bg-zinc-950 text-zinc-100 p-8">', type: 'add' },
        {
          text: '      <header className="mb-8 flex items-center justify-between border-b border-zinc-800 pb-4">',
          type: 'add',
        },
        { text: '        <div>', type: 'add' },
        { text: '          <h1 className="text-2xl font-bold">Enterprise Realtime Analytics</h1>', type: 'add' },
        {
          text: '          <p className="text-sm text-zinc-400">React 19 + Zustand v5 + Recharts Engine</p>',
          type: 'add',
        },
        { text: '        </div>', type: 'add' },
        { text: '      </header>', type: 'add' },
        { text: '      <div className="grid grid-cols-1 gap-6 md:grid-cols-3">', type: 'add' },
        {
          text: '        <MetricCard title="Gross Revenue" value={`$${latest?.revenue.toLocaleString()}`} change="+14.2%" isPositive badge="USD" />',
          type: 'add',
        },
        {
          text: '        <MetricCard title="Active Users" value={latest?.activeUsers.toLocaleString()} change="+8.7%" isPositive badge="USERS" />',
          type: 'add',
        },
        {
          text: '        <MetricCard title="Conversion Rate" value={`${latest?.conversionRate}%`} change="+1.2%" isPositive badge="CR" />',
          type: 'add',
        },
        { text: '      </div>', type: 'add' },
        {
          text: '      <Suspense fallback={<div className="mt-8 h-64 rounded-xl bg-zinc-900 animate-pulse" />}>',
          type: 'add',
        },
        { text: '        <AnalyticsChart data={metrics} />', type: 'add' },
        { text: '      </Suspense>', type: 'add' },
        { text: '    </div>', type: 'add' },
        { text: '  );', type: 'add' },
        { text: '}', type: 'add' },
      ],
    },
    {
      kind: 'build_step',
      step: 'TypeScript Strict Type Checking ($ npx tsc --noEmit)',
      status: 'success',
      duration: 750,
      output: ['Checking 14 ts/tsx source files...', '✓ 0 type errors found across project AST.'],
    },
    {
      kind: 'test_execution',
      command: 'npx vitest run --coverage',
      framework: 'Vitest v2.1.0',
      summary: { total: 4, passed: 4, failed: 0, skipped: 0 },
      results: [
        { name: 'MetricCard renders props cleanly without re-render bloat', status: 'pass', duration: 18 },
        { name: 'useDashboardStore updates timeframe state with persistence', status: 'pass', duration: 24 },
        { name: 'AnalyticsChart dynamically imports lazy module chunk', status: 'pass', duration: 32 },
        { name: 'App renders 3 metric cards and loading suspense fallback', status: 'pass', duration: 42 },
      ],
    },
    {
      kind: 'deployment',
      target: 'Vercel Edge Network (Production)',
      status: 'success',
      url: 'https://zenith-dashboard-prod.vercel.app',
      output: [
        'Deploying build artifact (dist/) to Vercel Edge Cache...',
        'Edge Functions deployed across 18 regions.',
        '✓ Deployment complete in 1.8s (SSL Certificate active)',
      ],
    },
    {
      kind: 'summary',
      title: 'Enterprise React 19 Dashboard Created & Deployed',
      description:
        'Architected React 19 analytics dashboard with Zustand v5 store, dynamic code splitting, Vitest coverage, and Vercel edge deployment.',
      filesCreated: [
        'dashboard/src/store/useDashboardStore.ts',
        'dashboard/src/components/MetricCard.tsx',
        'dashboard/src/App.tsx',
      ],
      commandsExecuted: [
        'npx create-vite@latest dashboard',
        'npm install recharts zustand react-router-dom @tanstack/react-query',
        'npx tsc --noEmit',
        'npx vitest run --coverage',
      ],
      verified: [
        'React 19 Concurrent Root & Suspense Fallbacks',
        'Zustand v5 State Persistence & DevTools',
        'TypeScript Strict Mode AST Compilation',
        'Vitest Unit Suite (4 passed, 100% assertion pass rate)',
      ],
    },
  ],
};

export const reactDashboardScenario = (prompt: string): Scenario => createScenario(prompt, template);
