import { Scenario } from '../../../types/scenario';

let idCounter = 0;
const uid = () => `react_${++idCounter}`;

export const reactDashboardScenario = (prompt: string): Scenario => ({
  id: `react_dashboard_${Date.now()}`,
  mode: 'build',
  prompt,
  events: [
    {
      kind: 'thinking',
      id: uid(),
      thoughts: [
        { text: 'Setting up React 19 project with Vite', delay: 300 },
        { text: 'Configuring TypeScript and ESLint', delay: 350 },
        { text: 'Planning component architecture', delay: 400 },
        { text: 'Designing dashboard layout', delay: 300 },
      ],
      duration: 1500,
    },
    {
      kind: 'progress',
      id: uid(),
      label: 'Project Scaffolding',
      steps: [
        { label: 'Initialize Vite project', status: 'active' },
        { label: 'Install dependencies', status: 'pending' },
        { label: 'Configure TypeScript', status: 'pending' },
        { label: 'Set up folder structure', status: 'pending' },
      ],
    },
    {
      kind: 'terminal',
      id: uid(),
      command: 'npm create vite@latest dashboard -- --template react-ts',
      output: [
        'Scaffolding project in D:\\projects\\dashboard...',
        'Done.',
      ],
      duration: 1500,
    },
    {
      kind: 'terminal',
      id: uid(),
      command: 'npm install recharts@2 react-router-dom@7 zustand@5',
      output: [
        'added 42 packages in 3.2s',
        '',
        '12 packages are looking for funding',
        '  run `npm fund` for details',
      ],
      duration: 2500,
    },
    {
      kind: 'file_create',
      id: uid(),
      filePath: 'dashboard/src/App.tsx',
      directory: 'dashboard/src/',
      language: 'tsx',
      lines: [
        { text: 'import { BrowserRouter, Routes, Route } from "react-router-dom";', type: 'add' },
        { text: 'import { DashboardLayout } from "./layouts/DashboardLayout";', type: 'add' },
        { text: 'import { OverviewPage } from "./pages/OverviewPage";', type: 'add' },
        { text: 'import { AnalyticsPage } from "./pages/AnalyticsPage";', type: 'add' },
        { text: '', type: 'add' },
        { text: 'export function App() {', type: 'add' },
        { text: '  return (', type: 'add' },
        { text: '    <BrowserRouter>', type: 'add' },
        { text: '      <Routes>', type: 'add' },
        { text: '        <Route element={<DashboardLayout />}>', type: 'add' },
        { text: '          <Route path="/" element={<OverviewPage />} />', type: 'add' },
        { text: '          <Route path="/analytics" element={<AnalyticsPage />} />', type: 'add' },
        { text: '        </Route>', type: 'add' },
        { text: '      </Routes>', type: 'add' },
        { text: '    </BrowserRouter>', type: 'add' },
        { text: '  );', type: 'add' },
        { text: '}', type: 'add' },
      ],
    },
    {
      kind: 'file_create',
      id: uid(),
      filePath: 'dashboard/src/components/MetricCard.tsx',
      directory: 'dashboard/src/components/',
      language: 'tsx',
      lines: [
        { text: 'interface MetricCardProps {', type: 'add' },
        { text: '  title: string;', type: 'add' },
        { text: '  value: string | number;', type: 'add' },
        { text: '  change?: number;', type: 'add' },
        { text: '  icon: React.ReactNode;', type: 'add' },
        { text: '}', type: 'add' },
        { text: '', type: 'add' },
        { text: 'export function MetricCard({ title, value, change, icon }: MetricCardProps) {', type: 'add' },
        { text: '  return (', type: 'add' },
        { text: '    <div className="metric-card">', type: 'add' },
        { text: '      <div className="metric-icon">{icon}</div>', type: 'add' },
        { text: '      <div className="metric-value">{value}</div>', type: 'add' },
        { text: '      <div className="metric-title">{title}</div>', type: 'add' },
        { text: '      {change !== undefined && (', type: 'add' },
        { text: '        <div className={`metric-change ${change >= 0 ? "positive" : "negative"}`}>', type: 'add' },
        { text: '          {change >= 0 ? "+" : ""}{change}%', type: 'add' },
        { text: '        </div>', type: 'add' },
        { text: '      )}', type: 'add' },
        { text: '    </div>', type: 'add' },
        { text: '  );', type: 'add' },
        { text: '}', type: 'add' },
      ],
    },
    {
      kind: 'file_create',
      id: uid(),
      filePath: 'dashboard/src/pages/OverviewPage.tsx',
      directory: 'dashboard/src/pages/',
      language: 'tsx',
      lines: [
        { text: 'import { MetricCard } from "../components/MetricCard";', type: 'add' },
        { text: 'import { BarChart, Bar, XAxis, YAxis, Tooltip } from "recharts";', type: 'add' },
        { text: '', type: 'add' },
        { text: 'const data = [', type: 'add' },
        { text: '  { name: "Jan", revenue: 4000, users: 2400 },', type: 'add' },
        { text: '  { name: "Feb", revenue: 3000, users: 1398 },', type: 'add' },
        { text: '  { name: "Mar", revenue: 5000, users: 3800 },', type: 'add' },
        { text: '];', type: 'add' },
        { text: '', type: 'add' },
        { text: 'export function OverviewPage() {', type: 'add' },
        { text: '  return (', type: 'add' },
        { text: '    <div className="overview">', type: 'add' },
        { text: '      <MetricCard title="Total Revenue" value="$12,000" change={12.5} icon="$" />', type: 'add' },
        { text: '      <MetricCard title="Active Users" value="7,598" change={8.2} icon="👤" />', type: 'add' },
        { text: '      <BarChart width={600} height={300} data={data}>', type: 'add' },
        { text: '        <XAxis dataKey="name" />', type: 'add' },
        { text: '        <YAxis />', type: 'add' },
        { text: '        <Tooltip />', type: 'add' },
        { text: '        <Bar dataKey="revenue" fill="#10b981" />', type: 'add' },
        { text: '      </BarChart>', type: 'add' },
        { text: '    </div>', type: 'add' },
        { text: '  );', type: 'add' },
        { text: '}', type: 'add' },
      ],
    },
    {
      kind: 'thinking',
      id: uid(),
      thoughts: [
        { text: 'Validating component structure', delay: 300 },
        { text: 'Running type checks', delay: 350 },
        { text: 'Building the project', delay: 400 },
      ],
      duration: 1100,
    },
    {
      kind: 'terminal',
      id: uid(),
      command: 'npm run build',
      output: [
        'vite v6.0.0 building for production...',
        '✓ 23 modules transformed.',
        'dist/index.html                   0.46 kB │ gzip:  0.30 kB',
        'dist/assets/index-Dk4dF2m.css     1.24 kB │ gzip:  0.65 kB',
        'dist/assets/index-Cv3xY1qJ.js   142.85 kB │ gzip: 45.72 kB',
        '✓ built in 1.84s',
      ],
      duration: 2500,
    },
    {
      kind: 'summary',
      id: uid(),
      title: 'React Dashboard Created',
      description: 'A React 19 dashboard with Recharts visualizations, Zustand state management, and React Router navigation.',
      filesCreated: [
        'dashboard/src/App.tsx',
        'dashboard/src/components/MetricCard.tsx',
        'dashboard/src/pages/OverviewPage.tsx',
      ],
      commandsExecuted: [
        'npm create vite@latest',
        'npm install recharts react-router-dom zustand',
        'npm run build',
      ],
      verified: [
        'TypeScript compilation',
        'Build output',
        'Component exports',
        'Route configuration',
      ],
    },
  ],
});
