import type { ProviderId, ProviderMeta } from './types';

export const PROVIDER_CATALOG: Record<ProviderId, ProviderMeta> = {
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter AI',
    description: 'Unified router access to 100+ top open and proprietary models',
    defaultModel: 'openrouter/auto',
    swatch: ['#6366F1', '#818CF8', '#A5B4FC', '#C7D2FE'],
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, placeholder: 'sk-or-v1-...' },
      { key: 'model', label: 'Default Model', type: 'select', required: true, defaultValue: 'openrouter/auto' },
      { key: 'baseUrl', label: 'Base URL', type: 'text', defaultValue: 'https://openrouter.ai/api/v1' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 30000 },
    ],
    availableModels: [
      { id: 'openrouter/auto', name: 'OpenRouter Auto Router', description: 'Optimal model router' },
      { id: 'anthropic/claude-3.5-sonnet', name: 'Claude 3.5 Sonnet', description: 'State-of-the-art coding model' },
      { id: 'openai/gpt-4o', name: 'OpenAI GPT-4o', description: 'Flagship multimodal model' },
      { id: 'google/gemini-pro-1.5', name: 'Gemini 1.5 Pro', description: '2M token context window' },
      { id: 'meta-llama/llama-3.3-70b-instruct', name: 'Llama 3.3 70B', description: 'Top open-weight LLM' },
    ],
  },
  openai: {
    id: 'openai',
    name: 'OpenAI Direct',
    description: 'Official OpenAI GPT-4o, o1, and o3-mini developer API',
    defaultModel: 'gpt-4o',
    swatch: ['#10A37F', '#1A7F64', '#26D07C', '#58F0A7'],
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, placeholder: 'sk-proj-...' },
      { key: 'model', label: 'Default Model', type: 'select', required: true, defaultValue: 'gpt-4o' },
      { key: 'organizationId', label: 'Organization ID', type: 'text', placeholder: 'org-...' },
      { key: 'baseUrl', label: 'Base URL', type: 'text', defaultValue: 'https://api.openai.com/v1' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 30000 },
    ],
    availableModels: [
      { id: 'gpt-4o', name: 'GPT-4o Omnimodal', description: 'High intelligence & speed' },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini', description: 'Cost efficient & fast' },
      { id: 'o1', name: 'OpenAI o1 Reasoning', description: 'Advanced reasoning engine' },
      { id: 'o3-mini', name: 'OpenAI o3 Mini', description: 'Fast code reasoning model' },
    ],
  },
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic Claude',
    description: 'Official Anthropic Claude 3.5 Sonnet, Haiku, and Opus API',
    defaultModel: 'claude-3-5-sonnet-latest',
    swatch: ['#D97706', '#F59E0B', '#FBBF24', '#FDE68A'],
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, placeholder: 'sk-ant-api03-...' },
      {
        key: 'model',
        label: 'Default Model',
        type: 'select',
        required: true,
        defaultValue: 'claude-3-5-sonnet-latest',
      },
      { key: 'baseUrl', label: 'Base URL', type: 'text', defaultValue: 'https://api.anthropic.com' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 30000 },
    ],
    availableModels: [
      { id: 'claude-3-5-sonnet-latest', name: 'Claude 3.5 Sonnet', description: 'Premier coding & analysis' },
      { id: 'claude-3-5-haiku-latest', name: 'Claude 3.5 Haiku', description: 'Ultra-fast sub-agent model' },
      { id: 'claude-3-opus-latest', name: 'Claude 3 Opus', description: 'Deep reasoning engine' },
    ],
  },
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    description: 'Google AI Studio Gemini 1.5 Pro, Flash, and 2.0 Flash models',
    defaultModel: 'gemini-1.5-pro',
    swatch: ['#2563EB', '#3B82F6', '#60A5FA', '#93C5FD'],
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, placeholder: 'AIzaSy...' },
      { key: 'model', label: 'Default Model', type: 'select', required: true, defaultValue: 'gemini-1.5-pro' },
      { key: 'baseUrl', label: 'Base URL', type: 'text', defaultValue: 'https://generativelanguage.googleapis.com' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 30000 },
    ],
    availableModels: [
      { id: 'gemini-1.5-pro', name: 'Gemini 1.5 Pro', description: 'Long context & deep analysis' },
      { id: 'gemini-1.5-flash', name: 'Gemini 1.5 Flash', description: 'High speed lightweight model' },
      { id: 'gemini-2.0-flash-exp', name: 'Gemini 2.0 Flash', description: 'Next-gen experimental speed' },
    ],
  },
  groq: {
    id: 'groq',
    name: 'Groq LPU Acceleration',
    description: 'Ultra-low latency inference engine powering Llama 3.3 & DeepSeek',
    defaultModel: 'llama-3.3-70b-versatile',
    swatch: ['#F97316', '#FB923C', '#FDBA74', '#FED7AA'],
    fields: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, placeholder: 'gsk_...' },
      { key: 'model', label: 'Default Model', type: 'select', required: true, defaultValue: 'llama-3.3-70b-versatile' },
      { key: 'baseUrl', label: 'Base URL', type: 'text', defaultValue: 'https://api.groq.com/openai/v1' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 15000 },
    ],
    availableModels: [
      { id: 'llama-3.3-70b-versatile', name: 'Llama 3.3 70B Versatile', description: 'Top performance LPU execution' },
      { id: 'mixtral-8x7b-32768', name: 'Mixtral 8x7B', description: 'High speed mixture of experts' },
      { id: 'deepseek-r1-distill-llama-70b', name: 'DeepSeek R1 Llama 70B', description: 'Distilled reasoning model' },
    ],
  },
  custom: {
    id: 'custom',
    name: 'Custom Endpoint (Ollama / vLLM / Local)',
    description: 'Connect to local Ollama, LM Studio, vLLM, or custom OpenAI-compatible server',
    defaultModel: 'llama3.2:latest',
    swatch: ['#10B981', '#34D399', '#6EE7B7', '#A7F3D0'],
    fields: [
      {
        key: 'baseUrl',
        label: 'Base Endpoint URL',
        type: 'text',
        required: true,
        defaultValue: 'http://localhost:11434/v1',
        placeholder: 'http://localhost:11434/v1',
      },
      {
        key: 'model',
        label: 'Model Identifier',
        type: 'text',
        required: true,
        defaultValue: 'llama3.2:latest',
        placeholder: 'llama3.2:latest',
      },
      { key: 'apiKey', label: 'API Key (Optional)', type: 'password', placeholder: 'Not required for local Ollama' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 60000 },
    ],
    availableModels: [
      { id: 'llama3.2:latest', name: 'Ollama Llama 3.2', description: 'Local default model' },
      { id: 'qwen2.5-coder:7b', name: 'Qwen 2.5 Coder 7B', description: 'Specialized local code model' },
      { id: 'deepseek-r1:14b', name: 'DeepSeek R1 14B Local', description: 'Local reasoning engine' },
    ],
  },
};
