@echo off
echo Setting up Python virtual environment .lib-venv...
python -m venv .lib-venv
echo Upgrading pip...
call .lib-venv\Scripts\python -m pip install --upgrade pip
echo Installing requirements...
call .lib-venv\Scripts\python -m pip install -r requirements.txt
echo Setup complete!
