from __future__ import annotations

from collections.abc import Iterator

SEED_VERSION = 1

DEFAULTS: dict = {
    "contextWindow": 128000,
    "maxOutputTokens": 32768,
}

PROVIDERS: list[dict] = [
    {
        "id": "gemini",
        "name": "Google AI Studio",
        "description": (
            "Google Gemini AI models via AI Studio. Free tier with generous "
            "quotas. Supports thinking, function calling, multimodal."
        ),
        "adapter": "gemini",
        "litellmPrefix": "gemini/",
        "baseUrl": "https://generativelanguage.googleapis.com",
        "requiresApiKey": True,
        "firstClass": True,
        "customFlow": False,
        "defaultModelId": "gemini/gemini-3.5-flash-lite",
        "apiKeyEnv": [
            "GOOGLE_AI_STUDIO",
            "google_ai_studio",
            "GOOGLE_API_KEY",
            "GEMINI_API_KEY",
        ],
        "apiKeyPrefixHint": "AQ.",
        "baseStyle": "gemini",
        "supportsPromptCaching": True,
        "supportsThinkingHeaders": False,
        "rateLimit": {"requests_per_minute": 15},
        "swatch": ["#4285F4", "#34A853", "#FBBC05"],
        "capabilities": {"streaming": True, "thinking": True, "function_calling": True},
        "sortOrder": 0,
        "source": "builtin",
        "models": [
            {
                "key": "gemini/gemini-3.5-flash-lite",
                "providerId": "gemini",
                "id": "gemini-3.5-flash-lite",
                "name": "Gemini 3.5 Flash-Lite",
                "description": (
                    "Lightweight 3.5 Flash. Ultra-fast (1.6s avg), no thinking overhead. "
                    "10/10 benchmark. Best speed/quality ratio."
                ),
                "contextWindow": 1048576,
                "parameters": None,
                "architecture": "Dense Transformer",
                "inputModalities": ["text", "image"],
                "outputModalities": ["text"],
                "tags": ["ultra-fast", "lightweight", "latest-gen", "default"],
                "capabilities": {
                    "function_calling": True,
                    "structured_output": True,
                    "reasoning": False,
                    "thinking": False,
                    "supports_temperature": False,
                },
                "speedTier": "fast",
                "bestFor": ["quick responses", "simple coding", "batch processing"],
                "pricing": {"input": 0.075, "output": 0.3, "cache_read": 0.015},
                "isDefault": True,
                "tokenizer": "o200k_base",
                "promptTier": "compact",
                "source": "builtin",
            },
            {
                "key": "gemini/gemini-3.5-flash",
                "providerId": "gemini",
                "id": "gemini-3.5-flash",
                "name": "Gemini 3.5 Flash",
                "description": (
                    "Latest generation flash model. Thinking support. Fast with strong "
                    "reasoning. FC confirmed."
                ),
                "contextWindow": 1048576,
                "parameters": None,
                "architecture": "Dense Transformer",
                "inputModalities": ["text", "image"],
                "outputModalities": ["text"],
                "tags": ["fast", "thinking", "latest-gen"],
                "capabilities": {
                    "function_calling": True,
                    "structured_output": True,
                    "reasoning": True,
                    "thinking": True,
                    "supports_temperature": False,
                },
                "speedTier": "fast",
                "bestFor": ["general coding", "reasoning", "fast responses"],
                "pricing": {"input": 0.15, "output": 0.6, "cache_read": 0.03},
                "isDefault": False,
                "tokenizer": "o200k_base",
                "promptTier": "compact",
                "source": "builtin",
            },
            {
                "key": "gemini/gemini-2.5-pro",
                "providerId": "gemini",
                "id": "gemini-2.5-pro",
                "name": "Gemini 2.5 Pro",
                "description": "Google's most capable model. Advanced reasoning and code generation. 1M context.",
                "contextWindow": 1048576,
                "parameters": None,
                "architecture": "Dense Transformer",
                "inputModalities": ["text", "image", "audio", "video"],
                "outputModalities": ["text"],
                "tags": ["frontier", "reasoning", "code", "production"],
                "capabilities": {
                    "function_calling": True,
                    "structured_output": True,
                    "reasoning": True,
                    "thinking": True,
                },
                "speedTier": "moderate",
                "bestFor": ["complex coding", "reasoning tasks", "agentic workflows"],
                "pricing": {"input": 1.25, "output": 5.0, "cache_read": 0.25},
                "isDefault": False,
                "tokenizer": "o200k_base",
                "promptTier": "flagship",
                "source": "builtin",
            },
            {
                "key": "gemini/gemini-3.1-pro-preview",
                "providerId": "gemini",
                "id": "gemini-3.1-pro-preview",
                "name": "Gemini 3.1 Pro Preview",
                "description": "Latest pro preview. Strongest reasoning and code generation.",
                "contextWindow": 1048576,
                "parameters": None,
                "architecture": "Dense Transformer",
                "inputModalities": ["text", "image"],
                "outputModalities": ["text"],
                "tags": ["preview", "frontier", "latest-gen"],
                "capabilities": {
                    "function_calling": True,
                    "structured_output": True,
                    "reasoning": True,
                    "thinking": True,
                    "supports_temperature": False,
                },
                "speedTier": "moderate",
                "bestFor": ["complex coding", "multi-step agentic tasks", "production code"],
                "pricing": {"input": 1.25, "output": 5.0, "cache_read": 0.25},
                "isDefault": False,
                "tokenizer": "o200k_base",
                "promptTier": "flagship",
                "source": "builtin",
            },
        ],
    },
    {
        "id": "groq",
        "name": "Groq",
        "description": (
            "Ultra-fast inference on Groq LPU. OpenAI-compatible API with "
            "function calling support. Free tier: 30 RPM, 1K RPD on most models."
        ),
        "adapter": "groq",
        "litellmPrefix": "groq/",
        "baseUrl": "https://api.groq.com/openai/v1",
        "requiresApiKey": True,
        "firstClass": True,
        "customFlow": False,
        "defaultModelId": "groq/llama-3.3-70b-versatile",
        "apiKeyEnv": ["GROQ_API_KEY", "groq_api_key"],
        "apiKeyPrefixHint": "gsk_",
        "baseStyle": "",
        "supportsPromptCaching": False,
        "supportsThinkingHeaders": False,
        "swatch": ["#F55036", "#FF6B52", "#E03A24"],
        "capabilities": {"streaming": True, "thinking": False, "function_calling": True},
        "sortOrder": 1,
        "source": "builtin",
        "models": [
            {
                "key": "groq/llama-3.3-70b-versatile",
                "providerId": "groq",
                "id": "llama-3.3-70b-versatile",
                "name": "Llama 3.3 70B Versatile",
                "description": (
                    "Meta's 70B. Best Groq model — fast (1.3s avg), excellent tool calling, "
                    "10/10 benchmark. Default choice."
                ),
                "contextWindow": 128000,
                "parameters": "70B",
                "architecture": "Dense Transformer",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["high-quality", "production", "coding", "default"],
                "capabilities": {
                    "function_calling": True,
                    "structured_output": True,
                    "reasoning": False,
                    "thinking": False,
                },
                "speedTier": "fast",
                "bestFor": ["agentic coding", "complex tasks", "general purpose"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": True,
                "tokenizer": "",
                "promptTier": "flagship",
                "source": "builtin",
            },
            {
                "key": "groq/llama-3.1-8b-instant",
                "providerId": "groq",
                "id": "llama-3.1-8b-instant",
                "name": "Llama 3.1 8B Instant",
                "description": "Meta's 8B. Ultra-fast (1.7s), generous rate limits (14.4K RPD).",
                "contextWindow": 131072,
                "parameters": "8B",
                "architecture": "Dense Transformer",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["ultra-fast", "lightweight", "production"],
                "capabilities": {
                    "function_calling": True,
                    "structured_output": True,
                    "reasoning": False,
                    "thinking": False,
                },
                "speedTier": "fast",
                "bestFor": ["quick responses", "simple coding", "batch processing"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": False,
                "tokenizer": "",
                "promptTier": "compact",
                "source": "builtin",
            },
            {
                "key": "groq/openai/gpt-oss-20b",
                "providerId": "groq",
                "id": "openai/gpt-oss-20b",
                "name": "GPT OSS 20B",
                "description": (
                    "OpenAI's open-source 20B. Best value — fast (1.6s) + high quality + "
                    "clean tool calls. 10/10 benchmark."
                ),
                "contextWindow": 131072,
                "parameters": "20B",
                "architecture": "Dense Transformer",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["openai", "production", "coding", "best-value"],
                "capabilities": {
                    "function_calling": True,
                    "structured_output": True,
                    "reasoning": False,
                    "thinking": False,
                },
                "speedTier": "fast",
                "bestFor": ["general coding", "agentic workflows", "best bang-for-buck"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": False,
                "tokenizer": "",
                "promptTier": "flagship",
                "source": "builtin",
            },
            {
                "key": "groq/openai/gpt-oss-120b",
                "providerId": "groq",
                "id": "openai/gpt-oss-120b",
                "name": "GPT OSS 120B",
                "description": (
                    "OpenAI's largest open-source model. Highest quality among GPT OSS "
                    "(6.2s avg). Best tool calling."
                ),
                "contextWindow": 131072,
                "parameters": "120B",
                "architecture": "Dense Transformer",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["openai", "high-quality", "production"],
                "capabilities": {
                    "function_calling": True,
                    "structured_output": True,
                    "reasoning": False,
                    "thinking": False,
                },
                "speedTier": "moderate",
                "bestFor": ["complex coding", "agentic workflows", "high-quality output"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": False,
                "tokenizer": "",
                "promptTier": "flagship",
                "source": "builtin",
            },
            {
                "key": "groq/qwen/qwen3.6-27b",
                "providerId": "groq",
                "id": "qwen/qwen3.6-27b",
                "name": "Qwen 3.6 27B",
                "description": (
                    "Alibaba's 27B. Reasoning support. Slow (7.8s avg), outputs thinking "
                    "tags in responses. Good tool calling."
                ),
                "contextWindow": 131072,
                "parameters": "27B",
                "architecture": "Dense Transformer",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["reasoning", "preview", "slow-inference"],
                "capabilities": {
                    "function_calling": True,
                    "structured_output": True,
                    "reasoning": True,
                    "thinking": False,
                },
                "speedTier": "slow",
                "bestFor": ["reasoning tasks", "analysis", "complex coding"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": False,
                "tokenizer": "",
                "promptTier": "flagship",
                "source": "builtin",
            },
            {
                "key": "groq/openai/gpt-oss-safeguard-20b",
                "providerId": "groq",
                "id": "openai/gpt-oss-safeguard-20b",
                "name": "Safety GPT OSS 20B",
                "description": (
                    "OpenAI's open-source 20B safety-tuned model. Same architecture as "
                    "GPT OSS 20B with safety guardrails."
                ),
                "contextWindow": 131072,
                "parameters": "20B",
                "architecture": "Dense Transformer",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["openai", "production", "safety"],
                "capabilities": {
                    "function_calling": True,
                    "structured_output": True,
                    "reasoning": True,
                    "thinking": False,
                },
                "speedTier": "fast",
                "bestFor": ["general coding", "agentic workflows", "safety-sensitive tasks"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": False,
                "tokenizer": "",
                "promptTier": "flagship",
                "source": "builtin",
            },
            {
                "key": "groq/groq/compound",
                "providerId": "groq",
                "id": "groq/compound",
                "name": "Compound",
                "description": "Groq's in-house flagship. Ultra-fast inference on LPU.",
                "contextWindow": 131072,
                "parameters": "unknown",
                "architecture": "Dense Transformer",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["production", "fast", "groq"],
                "capabilities": {
                    "function_calling": False,
                    "structured_output": True,
                    "reasoning": False,
                    "thinking": False,
                },
                "speedTier": "fast",
                "bestFor": ["quick responses", "general purpose", "lightweight"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": False,
                "tokenizer": "",
                "promptTier": "flagship",
                "source": "builtin",
            },
            {
                "key": "groq/groq/compound-mini",
                "providerId": "groq",
                "id": "groq/compound-mini",
                "name": "Compound Mini",
                "description": "Groq's compact in-house model. Even faster, low-latency responses.",
                "contextWindow": 131072,
                "parameters": "unknown",
                "architecture": "Dense Transformer",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["production", "ultra-fast", "lightweight", "groq"],
                "capabilities": {
                    "function_calling": False,
                    "structured_output": True,
                    "reasoning": False,
                    "thinking": False,
                },
                "speedTier": "fast",
                "bestFor": ["quick responses", "batch processing", "simple tasks"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": False,
                "tokenizer": "",
                "promptTier": "compact",
                "source": "builtin",
            },
            {
                "key": "groq/allam-2-7b",
                "providerId": "groq",
                "id": "allam-2-7b",
                "name": "ALLaM-2-7b",
                "description": "SDAIA's bilingual Arabic/English 7B model. Strong for Arabic-language tasks.",
                "contextWindow": 4096,
                "parameters": "7B",
                "architecture": "Dense Transformer",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["production", "bilingual", "arabic"],
                "capabilities": {
                    "function_calling": False,
                    "structured_output": True,
                    "reasoning": False,
                    "thinking": False,
                },
                "speedTier": "fast",
                "bestFor": ["arabic text", "translation", "quick responses"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": False,
                "tokenizer": "",
                "promptTier": "compact",
                "source": "builtin",
            },
            {
                "key": "groq/meta-llama/llama-prompt-guard-2-22m",
                "providerId": "groq",
                "id": "meta-llama/llama-prompt-guard-2-22m",
                "name": "Llama Prompt Guard 2 22M",
                "description": "Meta's prompt-injection classifier. Special-purpose, not for general chat.",
                "contextWindow": 512,
                "parameters": "22M",
                "architecture": "Dense Transformer",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["safety", "classifier", "special-purpose"],
                "capabilities": {
                    "function_calling": False,
                    "structured_output": False,
                    "reasoning": False,
                    "thinking": False,
                },
                "speedTier": "fast",
                "bestFor": ["prompt safety", "classification"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": False,
                "tokenizer": "",
                "promptTier": "compact",
                "source": "builtin",
            },
            {
                "key": "groq/meta-llama/llama-prompt-guard-2-86m",
                "providerId": "groq",
                "id": "meta-llama/llama-prompt-guard-2-86m",
                "name": "Prompt Guard 2 86M",
                "description": "Meta's larger prompt-injection classifier. Special-purpose, not for general chat.",
                "contextWindow": 512,
                "parameters": "86M",
                "architecture": "Dense Transformer",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["safety", "classifier", "special-purpose"],
                "capabilities": {
                    "function_calling": False,
                    "structured_output": True,
                    "reasoning": False,
                    "thinking": False,
                },
                "speedTier": "fast",
                "bestFor": ["prompt safety", "classification"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": False,
                "tokenizer": "",
                "promptTier": "compact",
                "source": "builtin",
            },
        ],
    },
    {
        "id": "openrouter",
        "name": "OpenRouter",
        "description": (
            "Free tier inference via OpenRouter. OpenAI-compatible API with "
            "native function calling. All models use the :free suffix."
        ),
        "adapter": "openrouter",
        "litellmPrefix": "openai/",
        "baseUrl": "https://openrouter.ai/api/v1",
        "requiresApiKey": True,
        "firstClass": True,
        "customFlow": False,
        "defaultModelId": "openrouter/openrouter/free",
        "apiKeyEnv": ["OPENROUTER_API", "openrouter_api", "OPENROUTER_API_KEY"],
        "apiKeyPrefixHint": "sk-or-v1-",
        "baseStyle": "",
        "supportsPromptCaching": False,
        "supportsThinkingHeaders": False,
        "swatch": ["#7000FF", "#A033FF", "#6000DF"],
        "capabilities": {"streaming": True, "thinking": True, "function_calling": True},
        "sortOrder": 2,
        "source": "builtin",
        "models": [
            {
                "key": "openrouter/openrouter/free",
                "providerId": "openrouter",
                "id": "openrouter/free",
                "name": "Free Models Router",
                "description": (
                    "Meta router that randomly selects from available free models. "
                    "Supports tool calling, structured output, and reasoning. Model "
                    "varies per request."
                ),
                "contextWindow": 131072,
                "parameters": "varies",
                "architecture": "Router (meta)",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["router", "free", "meta", "default"],
                "capabilities": {
                    "function_calling": True,
                    "structured_output": True,
                    "reasoning": True,
                    "thinking": False,
                },
                "speedTier": "fast",
                "bestFor": ["free tier", "exploration", "general purpose"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": True,
                "tokenizer": "",
                "promptTier": "flagship",
                "source": "builtin",
            },
            {
                "key": "openrouter/poolside/laguna-xs-2.1:free",
                "providerId": "openrouter",
                "id": "poolside/laguna-xs-2.1:free",
                "name": "Poolside Laguna XS 2.1",
                "description": (
                    "Poolside 33B MoE. Free on OpenRouter. Good code quality. May be slow. "
                    "Verified: connects, FC works."
                ),
                "contextWindow": 262144,
                "parameters": "33B (MoE)",
                "architecture": "Mixture of Experts",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["free", "coding", "agentic"],
                "capabilities": {
                    "function_calling": True,
                    "structured_output": True,
                    "reasoning": True,
                    "thinking": False,
                },
                "speedTier": "moderate",
                "bestFor": ["agentic coding", "tool-heavy workflows", "free tier"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": False,
                "tokenizer": "",
                "promptTier": "flagship",
                "source": "builtin",
            },
            {
                "key": "openrouter/poolside/laguna-s-2.1:free",
                "providerId": "openrouter",
                "id": "poolside/laguna-s-2.1:free",
                "name": "Poolside Laguna S 2.1",
                "description": (
                    "Poolside larger S variant. Free on OpenRouter. Stronger reasoning than "
                    "XS. Verified: connects, FC works."
                ),
                "contextWindow": 262144,
                "parameters": "unknown",
                "architecture": "Mixture of Experts",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["free", "coding", "reasoning"],
                "capabilities": {
                    "function_calling": True,
                    "structured_output": True,
                    "reasoning": True,
                    "thinking": False,
                },
                "speedTier": "moderate",
                "bestFor": ["complex coding", "reasoning tasks", "free tier"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": False,
                "tokenizer": "",
                "promptTier": "flagship",
                "source": "builtin",
            },
            {
                "key": "openrouter/cohere/north-mini-code:free",
                "providerId": "openrouter",
                "id": "cohere/north-mini-code:free",
                "name": "Cohere North Mini Code",
                "description": (
                    "Cohere code-focused mini model. Free on OpenRouter. Supports tools and "
                    "reasoning. Verified: connects, FC works."
                ),
                "contextWindow": 131072,
                "parameters": "unknown",
                "architecture": "Dense Transformer",
                "inputModalities": ["text"],
                "outputModalities": ["text"],
                "tags": ["free", "code", "coding"],
                "capabilities": {
                    "function_calling": True,
                    "structured_output": True,
                    "reasoning": True,
                    "thinking": False,
                },
                "speedTier": "fast",
                "bestFor": ["code generation", "code explanation", "free tier"],
                "pricing": {"input": 0.0, "output": 0.0},
                "isDefault": False,
                "tokenizer": "",
                "promptTier": "compact",
                "source": "builtin",
            },
        ],
    },
    {
        "id": "openai_compatible",
        "name": "OpenAI Compatible",
        "description": (
            "Custom OpenAI-compatible API endpoint (vLLM, Ollama, LM Studio, "
            "or any OpenAI-shaped /v1 server, including OpenAI or Anthropic "
            "compatible gateways)."
        ),
        "adapter": "openai_compatible",
        "litellmPrefix": "openai/",
        "baseUrl": "",
        "requiresApiKey": False,
        "firstClass": True,
        "customFlow": True,
        "defaultModelId": "",
        "apiKeyEnv": [],
        "apiKeyPrefixHint": "",
        "baseStyle": "user",
        "supportsPromptCaching": False,
        "supportsThinkingHeaders": False,
        "swatch": ["#00A67E", "#008C6A", "#00664D"],
        "capabilities": {"streaming": True, "thinking": True, "function_calling": True},
        "sortOrder": 3,
        "source": "builtin",
        "models": [],
    },
]


def iter_builtin_models() -> Iterator[dict]:
    """Yield every builtin model across all providers."""
    for provider in PROVIDERS:
        yield from provider.get("models", [])
