"""Builtin provider/model catalog seed.

This replaces the SQL seed migrations (003/004/006/007/008). The catalog is
data-only: four first-class providers (gemini, groq, openrouter,
openai_compatible) per decision D3, with every currently-catalogued model
transcribed verbatim (decision D21).

Field naming follows the runtime's internal shapes so downstream consumers
(registry defaults, price resolution) need no mapping layer:
``capabilities`` mirrors the old ``model_capabilities_json`` content and
``pricing`` mirrors ``pricing_json``.

Bump :data:`SEED_VERSION` when builtin rows change; materialization refreshes
rows whose ``source == "builtin"`` and never touches user-added entries.
"""

from __future__ import annotations

SEED_VERSION = 1

DEFAULTS: dict = {
    "contextWindow": 128000,
    "maxOutputTokens": 32768,
}

PROVIDERS: list[dict] = [
    {
        "id": "gemini",
        "name": "Google AI Studio",
        "description": (
            "Google Gemini AI models via AI Studio. Free tier with generous "
            "quotas. Supports thinking, function calling, multimodal."
        ),
        "adapter": "gemini",
        "litellmPrefix": "gemini/",
        "baseUrl": "https://generativelanguage.googleapis.com",
        "requiresApiKey": True,
        "firstClass": True,
        "customFlow": False,
        "defaultModelId": "gemini/gemini-3.5-flash-lite",
        "apiKeyEnv": [
            "GOOGLE_AI_STUDIO",
            "google_ai_studio",
            "GOOGLE_API_KEY",
            "GEMINI_API_KEY",
        ],
        "apiKeyPrefixHint": "AQ.",
        "baseStyle": "gemini",
        "supportsPromptCaching": True,
        "supportsThinkingHeaders": False,
        "rateLimit": {"requests_per_minute": 15},
        "swatch": ["#4285F4", "#34A853", "#FBBC05"],
        "capabilities": {"streaming": True, "thinking": True, "function_calling": True},
        "sortOrder": 0,
        "source": "builtin",
    },
    {
        "id": "groq",
        "name": "Groq",
        "description": (
            "Ultra-fast inference on Groq LPU. OpenAI-compatible API with "
            "function calling support. Free tier: 30 RPM, 1K RPD on most models."
        ),
        "adapter": "groq",
        "litellmPrefix": "groq/",
        "baseUrl": "https://api.groq.com/openai/v1",
        "requiresApiKey": True,
        "firstClass": True,
        "customFlow": False,
        "defaultModelId": "groq/llama-3.3-70b-versatile",
        "apiKeyEnv": ["GROQ_API_KEY", "groq_api_key"],
        "apiKeyPrefixHint": "gsk_",
        "baseStyle": "",
        "supportsPromptCaching": False,
        "supportsThinkingHeaders": False,
        "swatch": ["#F55036", "#FF6B52", "#E03A24"],
        "capabilities": {"streaming": True, "thinking": False, "function_calling": True},
        "sortOrder": 1,
        "source": "builtin",
    },
    {
        "id": "openrouter",
        "name": "OpenRouter",
        "description": (
            "Free tier inference via OpenRouter. OpenAI-compatible API with "
            "native function calling. All models use the :free suffix."
        ),
        "adapter": "openrouter",
        "litellmPrefix": "openai/",
        "baseUrl": "https://openrouter.ai/api/v1",
        "requiresApiKey": True,
        "firstClass": True,
        "customFlow": False,
        "defaultModelId": "openrouter/openrouter/free",
        "apiKeyEnv": ["OPENROUTER_API", "openrouter_api", "OPENROUTER_API_KEY"],
        "apiKeyPrefixHint": "sk-or-v1-",
        "baseStyle": "",
        "supportsPromptCaching": False,
        "supportsThinkingHeaders": False,
        "swatch": ["#7000FF", "#A033FF", "#6000DF"],
        "capabilities": {"streaming": True, "thinking": True, "function_calling": True},
        "sortOrder": 2,
        "source": "builtin",
    },
    {
        "id": "openai_compatible",
        "name": "OpenAI Compatible",
        "description": (
            "Custom OpenAI-compatible API endpoint (vLLM, Ollama, LM Studio, "
            "or any OpenAI-shaped /v1 server, including OpenAI or Anthropic "
            "compatible gateways)."
        ),
        "adapter": "openai_compatible",
        "litellmPrefix": "openai/",
        "baseUrl": "",
        "requiresApiKey": False,
        "firstClass": True,
        "customFlow": True,
        "defaultModelId": "",
        "apiKeyEnv": [],
        "apiKeyPrefixHint": "",
        "baseStyle": "user",
        "supportsPromptCaching": False,
        "supportsThinkingHeaders": False,
        "swatch": ["#00A67E", "#008C6A", "#00664D"],
        "capabilities": {"streaming": True, "thinking": True, "function_calling": True},
        "sortOrder": 3,
        "source": "builtin",
    },
]


def _m(
    provider: str,
    id: str,
    name: str,
    description: str,
    context_window: int,
    parameters: str | None,
    architecture: str | None,
    input_modalities: list[str],
    output_modalities: list[str],
    tags: list[str],
    capabilities: dict,
    speed_tier: str,
    best_for: list[str],
    pricing: dict,
    is_default: bool,
    tokenizer: str,
    prompt_tier: str,
) -> dict:
    return {
        "key": f"{provider}/{id}",
        "providerId": provider,
        "id": id,
        "name": name,
        "description": description,
        "contextWindow": context_window,
        "parameters": parameters,
        "architecture": architecture,
        "inputModalities": input_modalities,
        "outputModalities": output_modalities,
        "tags": tags,
        "capabilities": capabilities,
        "speedTier": speed_tier,
        "bestFor": best_for,
        "pricing": pricing,
        "isDefault": is_default,
        "tokenizer": tokenizer,
        "promptTier": prompt_tier,
        "source": "builtin",
    }


_MODELS: list[dict] = [
    # ── gemini ────────────────────────────────────────────────────────
    _m(
        "gemini",
        "gemini-3.5-flash-lite",
        "Gemini 3.5 Flash-Lite",
        "Lightweight 3.5 Flash. Ultra-fast (1.6s avg), no thinking overhead. "
        "10/10 benchmark. Best speed/quality ratio.",
        1048576,
        None,
        "Dense Transformer",
        ["text", "image"],
        ["text"],
        ["ultra-fast", "lightweight", "latest-gen", "default"],
        {
            "function_calling": True,
            "structured_output": True,
            "reasoning": False,
            "thinking": False,
            "supports_temperature": False,
        },
        "fast",
        ["quick responses", "simple coding", "batch processing"],
        {"input": 0.075, "output": 0.3, "cache_read": 0.015},
        True,
        "o200k_base",
        "compact",
    ),
    _m(
        "gemini",
        "gemini-3.5-flash",
        "Gemini 3.5 Flash",
        "Latest generation flash model. Thinking support. Fast with strong "
        "reasoning. FC confirmed.",
        1048576,
        None,
        "Dense Transformer",
        ["text", "image"],
        ["text"],
        ["fast", "thinking", "latest-gen"],
        {
            "function_calling": True,
            "structured_output": True,
            "reasoning": True,
            "thinking": True,
            "supports_temperature": False,
        },
        "fast",
        ["general coding", "reasoning", "fast responses"],
        {"input": 0.15, "output": 0.6, "cache_read": 0.03},
        False,
        "o200k_base",
        "compact",
    ),
    _m(
        "gemini",
        "gemini-2.5-pro",
        "Gemini 2.5 Pro",
        "Google's most capable model. Advanced reasoning and code generation. 1M context.",
        1048576,
        None,
        "Dense Transformer",
        ["text", "image", "audio", "video"],
        ["text"],
        ["frontier", "reasoning", "code", "production"],
        {
            "function_calling": True,
            "structured_output": True,
            "reasoning": True,
            "thinking": True,
        },
        "moderate",
        ["complex coding", "reasoning tasks", "agentic workflows"],
        {"input": 1.25, "output": 5.0, "cache_read": 0.25},
        False,
        "o200k_base",
        "flagship",
    ),
    _m(
        "gemini",
        "gemini-3.1-pro-preview",
        "Gemini 3.1 Pro Preview",
        "Latest pro preview. Strongest reasoning and code generation.",
        1048576,
        None,
        "Dense Transformer",
        ["text", "image"],
        ["text"],
        ["preview", "frontier", "latest-gen"],
        {
            "function_calling": True,
            "structured_output": True,
            "reasoning": True,
            "thinking": True,
            "supports_temperature": False,
        },
        "moderate",
        ["complex coding", "multi-step agentic tasks", "production code"],
        {"input": 1.25, "output": 5.0, "cache_read": 0.25},
        False,
        "o200k_base",
        "flagship",
    ),
    # ── groq ──────────────────────────────────────────────────────────
    _m(
        "groq",
        "llama-3.3-70b-versatile",
        "Llama 3.3 70B Versatile",
        "Meta's 70B. Best Groq model — fast (1.3s avg), excellent tool calling, "
        "10/10 benchmark. Default choice.",
        128000,
        "70B",
        "Dense Transformer",
        ["text"],
        ["text"],
        ["high-quality", "production", "coding", "default"],
        {
            "function_calling": True,
            "structured_output": True,
            "reasoning": False,
            "thinking": False,
        },
        "fast",
        ["agentic coding", "complex tasks", "general purpose"],
        {"input": 0.0, "output": 0.0},
        True,
        "",
        "flagship",
    ),
    _m(
        "groq",
        "llama-3.1-8b-instant",
        "Llama 3.1 8B Instant",
        "Meta's 8B. Ultra-fast (1.7s), generous rate limits (14.4K RPD).",
        131072,
        "8B",
        "Dense Transformer",
        ["text"],
        ["text"],
        ["ultra-fast", "lightweight", "production"],
        {
            "function_calling": True,
            "structured_output": True,
            "reasoning": False,
            "thinking": False,
        },
        "fast",
        ["quick responses", "simple coding", "batch processing"],
        {"input": 0.0, "output": 0.0},
        False,
        "",
        "compact",
    ),
    _m(
        "groq",
        "openai/gpt-oss-20b",
        "GPT OSS 20B",
        "OpenAI's open-source 20B. Best value — fast (1.6s) + high quality + "
        "clean tool calls. 10/10 benchmark.",
        131072,
        "20B",
        "Dense Transformer",
        ["text"],
        ["text"],
        ["openai", "production", "coding", "best-value"],
        {
            "function_calling": True,
            "structured_output": True,
            "reasoning": False,
            "thinking": False,
        },
        "fast",
        ["general coding", "agentic workflows", "best bang-for-buck"],
        {"input": 0.0, "output": 0.0},
        False,
        "",
        "flagship",
    ),
    _m(
        "groq",
        "openai/gpt-oss-120b",
        "GPT OSS 120B",
        "OpenAI's largest open-source model. Highest quality among GPT OSS "
        "(6.2s avg). Best tool calling.",
        131072,
        "120B",
        "Dense Transformer",
        ["text"],
        ["text"],
        ["openai", "high-quality", "production"],
        {
            "function_calling": True,
            "structured_output": True,
            "reasoning": False,
            "thinking": False,
        },
        "moderate",
        ["complex coding", "agentic workflows", "high-quality output"],
        {"input": 0.0, "output": 0.0},
        False,
        "",
        "flagship",
    ),
    _m(
        "groq",
        "qwen/qwen3.6-27b",
        "Qwen 3.6 27B",
        "Alibaba's 27B. Reasoning support. Slow (7.8s avg), outputs thinking "
        "tags in responses. Good tool calling.",
        131072,
        "27B",
        "Dense Transformer",
        ["text"],
        ["text"],
        ["reasoning", "preview", "slow-inference"],
        {
            "function_calling": True,
            "structured_output": True,
            "reasoning": True,
            "thinking": False,
        },
        "slow",
        ["reasoning tasks", "analysis", "complex coding"],
        {"input": 0.0, "output": 0.0},
        False,
        "",
        "flagship",
    ),
    _m(
        "groq",
        "openai/gpt-oss-safeguard-20b",
        "Safety GPT OSS 20B",
        "OpenAI's open-source 20B safety-tuned model. Same architecture as "
        "GPT OSS 20B with safety guardrails.",
        131072,
        "20B",
        "Dense Transformer",
        ["text"],
        ["text"],
        ["openai", "production", "safety"],
        {
            "function_calling": True,
            "structured_output": True,
            "reasoning": True,
            "thinking": False,
        },
        "fast",
        ["general coding", "agentic workflows", "safety-sensitive tasks"],
        {"input": 0.0, "output": 0.0},
        False,
        "",
        "flagship",
    ),
    _m(
        "groq",
        "groq/compound",
        "Compound",
        "Groq's in-house flagship. Ultra-fast inference on LPU.",
        131072,
        "unknown",
        "Dense Transformer",
        ["text"],
        ["text"],
        ["production", "fast", "groq"],
        {
            "function_calling": False,
            "structured_output": True,
            "reasoning": False,
            "thinking": False,
        },
        "fast",
        ["quick responses", "general purpose", "lightweight"],
        {"input": 0.0, "output": 0.0},
        False,
        "",
        "flagship",
    ),
    _m(
        "groq",
        "groq/compound-mini",
        "Compound Mini",
        "Groq's compact in-house model. Even faster, low-latency responses.",
        131072,
        "unknown",
        "Dense Transformer",
        ["text"],
        ["text"],
        ["production", "ultra-fast", "lightweight", "groq"],
        {
            "function_calling": False,
            "structured_output": True,
            "reasoning": False,
            "thinking": False,
        },
        "fast",
        ["quick responses", "batch processing", "simple tasks"],
        {"input": 0.0, "output": 0.0},
        False,
        "",
        "compact",
    ),
    _m(
        "groq",
        "allam-2-7b",
        "ALLaM-2-7b",
        "SDAIA's bilingual Arabic/English 7B model. Strong for Arabic-language tasks.",
        4096,
        "7B",
        "Dense Transformer",
        ["text"],
        ["text"],
        ["production", "bilingual", "arabic"],
        {
            "function_calling": False,
            "structured_output": True,
            "reasoning": False,
            "thinking": False,
        },
        "fast",
        ["arabic text", "translation", "quick responses"],
        {"input": 0.0, "output": 0.0},
        False,
        "",
        "compact",
    ),
    _m(
        "groq",
        "meta-llama/llama-prompt-guard-2-22m",
        "Llama Prompt Guard 2 22M",
        "Meta's prompt-injection classifier. Special-purpose, not for general chat.",
        512,
        "22M",
        "Dense Transformer",
        ["text"],
        ["text"],
        ["safety", "classifier", "special-purpose"],
        {
            "function_calling": False,
            "structured_output": False,
            "reasoning": False,
            "thinking": False,
        },
        "fast",
        ["prompt safety", "classification"],
        {"input": 0.0, "output": 0.0},
        False,
        "",
        "compact",
    ),
    _m(
        "groq",
        "meta-llama/llama-prompt-guard-2-86m",
        "Prompt Guard 2 86M",
        "Meta's larger prompt-injection classifier. Special-purpose, not for general chat.",
        512,
        "86M",
        "Dense Transformer",
        ["text"],
        ["text"],
        ["safety", "classifier", "special-purpose"],
        {
            "function_calling": False,
            "structured_output": True,
            "reasoning": False,
            "thinking": False,
        },
        "fast",
        ["prompt safety", "classification"],
        {"input": 0.0, "output": 0.0},
        False,
        "",
        "compact",
    ),
    # ── openrouter ────────────────────────────────────────────────────
    _m(
        "openrouter",
        "openrouter/free",
        "Free Models Router",
        "Meta router that randomly selects from available free models. "
        "Supports tool calling, structured output, and reasoning. Model "
        "varies per request.",
        131072,
        "varies",
        "Router (meta)",
        ["text"],
        ["text"],
        ["router", "free", "meta", "default"],
        {
            "function_calling": True,
            "structured_output": True,
            "reasoning": True,
            "thinking": False,
        },
        "fast",
        ["free tier", "exploration", "general purpose"],
        {"input": 0.0, "output": 0.0},
        True,
        "",
        "flagship",
    ),
    _m(
        "openrouter",
        "poolside/laguna-xs-2.1:free",
        "Poolside Laguna XS 2.1",
        "Poolside 33B MoE. Free on OpenRouter. Good code quality. May be slow. "
        "Verified: connects, FC works.",
        262144,
        "33B (MoE)",
        "Mixture of Experts",
        ["text"],
        ["text"],
        ["free", "coding", "agentic"],
        {
            "function_calling": True,
            "structured_output": True,
            "reasoning": True,
            "thinking": False,
        },
        "moderate",
        ["agentic coding", "tool-heavy workflows", "free tier"],
        {"input": 0.0, "output": 0.0},
        False,
        "",
        "flagship",
    ),
    _m(
        "openrouter",
        "poolside/laguna-s-2.1:free",
        "Poolside Laguna S 2.1",
        "Poolside larger S variant. Free on OpenRouter. Stronger reasoning than "
        "XS. Verified: connects, FC works.",
        262144,
        "unknown",
        "Mixture of Experts",
        ["text"],
        ["text"],
        ["free", "coding", "reasoning"],
        {
            "function_calling": True,
            "structured_output": True,
            "reasoning": True,
            "thinking": False,
        },
        "moderate",
        ["complex coding", "reasoning tasks", "free tier"],
        {"input": 0.0, "output": 0.0},
        False,
        "",
        "flagship",
    ),
    _m(
        "openrouter",
        "cohere/north-mini-code:free",
        "Cohere North Mini Code",
        "Cohere code-focused mini model. Free on OpenRouter. Supports tools and "
        "reasoning. Verified: connects, FC works.",
        131072,
        "unknown",
        "Dense Transformer",
        ["text"],
        ["text"],
        ["free", "code", "coding"],
        {
            "function_calling": True,
            "structured_output": True,
            "reasoning": True,
            "thinking": False,
        },
        "fast",
        ["code generation", "code explanation", "free tier"],
        {"input": 0.0, "output": 0.0},
        False,
        "",
        "compact",
    ),
]

MODELS_BY_KEY: dict[str, dict] = {m["key"]: m for m in _MODELS}
